import {test} from 'node:test';
import assert from 'node:assert/strict';
import {analyzeTurnPlan,previewQuantity} from '../src/lib/turn-analysis';
import {newTurnPlan,saveTurnPlan,validateTurnPlans,removeTurnPlan} from '../src/lib/turn-plan-storage';
import {scenarioEvidenceKey} from '../src/lib/scenario-storage';
import {parseReport} from '../src/lib/wwbp/parser';
import {decodeWorkspace} from '../src/lib/workspace';
import {validateCloudSave,mergeLocalWorkspace} from '../src/lib/cloud-validation';
import type {TurnPlan} from '../src/lib/turn-plan-types';
import type {Geography,Workspace} from '../src/lib/wwbp/types';

const key='a'.repeat(64);
const atlas:Record<string,Geography>=Object.fromEntries(['AAA','BBB','CCC','DDD','WWW','WXX'].map(code=>[code,{name:code,x:0,y:0,surface:code==='DDD'?[]:['AAA','BBB','CCC','WWW'].filter(c=>c!==code),air:code==='DDD'?['BBB']:[],canals:code==='WXX'?[{target:'BBB',gate:'DDD'}]:[]}]));
function report(player:number,turn=2){const code={1:'AAA',2:'CCC',3:'BBB'}[player]!,army={1:20,2:10,3:24}[player]!;return parseReport(`Game COORD-DEMO, Turn ${turn}, Player [${player}:FICTIONAL ${player}]
Spies=5 CounterSpies=2 Dollars=100
Multipliers=(I100 A100 N100 F100 M100 X100)
Forces under your control:
${code} ${army} 0 0 2 0 6 80
 ${army} 0 0 2 0 6
Occupied Countries
AAA [1:FICTIONAL 1] Army=20 AirF=0 Navy=0 ABMs=0 Missiles=2 Industry=6 TaxBase=30
BBB [3:FICTIONAL 3] Army=24 AirF=0 Navy=0 ABMs=0 Missiles=2 Industry=6 TaxBase=30
CCC [2:FICTIONAL 2] Army=10 AirF=0 Navy=0 ABMs=0 Missiles=2 Industry=6 TaxBase=30
Visible forces of all players:
`,`p${player}-t${turn}.txt`);}
const reports=()=>[report(1),report(2),report(3)];
function plan():TurnPlan{const p=newTurnPlan(2);p.evidenceKey=key;p.sets=[{player:1,reportTurn:2,text:'ORDERS\r\n@AAA\r\nAC20BBB\r\nEND',standingReviewed:true},{player:2,reportTurn:2,text:'ORDERS\n@CCC AB10BBB\nEND',standingReviewed:true}];p.reviews.BBB={defense:{Army:24,AirF:0,Navy:0,ABMs:0},unknownOrders:true,isolated:true,note:'Defender holds 24 Army with no extra builds or support.'};return p;}
const analyze=(p=plan(),rs=reports())=>analyzeTurnPlan(p,rs,'COORD-DEMO',atlas,key);
const opponent=(p:TurnPlan,text='ORDERS\nEND')=>{p.sets.push({player:3,reportTurn:2,text,standingReviewed:true});return p;};
const messages=(a:ReturnType<typeof analyze>)=>[...a.findings.map(f=>f.message),...a.battles.flatMap(b=>b.errors)].join('\n');

test('two actual order sets combine only committed forces with original line attribution',()=>{const a=analyze();assert.equal(a.battles[0].estimates[1].capture,'uncertain');assert.equal(a.orders[0].line,3);assert.equal(a.orders[0].player,1);assert.ok(Math.abs(a.battles[0].estimates[1].attackArmy-10.8)<1e-9);assert.equal(a.battles[0].conditional,true);assert.match(messages(a),/opposing orders|proposed orders from the defender/);});
test('individually legal orders can miss the expected role and fail coordination',()=>{const p=plan();p.sets[1].text='ORDERS\n@CCC AS10BBB\nEND';p.expected=[{id:'exp',player:2,source:'CCC',target:'BBB',role:'bombard',quantity:10}];const a=analyze(p);assert.equal(a.findings.filter(f=>f.kind==='error').length,0);const finding=a.findings.find(f=>f.kind==='coordination'&&f.message.includes('only 0'));assert.equal(finding?.refs[0].token,'AS10BBB');assert.equal(a.battles[0].estimates[1].capture,'none');});
test('missing player, wrong destination and insufficient quantity produce expected-contribution findings',()=>{for(const text of ['', 'ORDERS\n@CCC AB10AAA\nEND','ORDERS\n@CCC AB2BBB\nEND']){const p=plan();if(text)p.sets[1].text=text;else p.sets.pop();p.expected=[{id:'x',player:2,source:'CCC',target:'BBB',role:'bombard',quantity:10}];assert.match(messages(analyze(p)),/Expected P2/);}});
test('global force commitments, duplicate orders, resource overspending and invalid range block results',()=>{for(const text of ['@AAA AC20BBB AB1CCC','@AAA AC10BBB AC10BBB','@ TS101\n@AAA AC20BBB','@DDD AC1BBB']){const p=plan();p.sets[0].text=`ORDERS\n${text}\nEND`;const a=analyze(p);assert.ok(a.findings.some(f=>f.kind==='error'));assert.ok(a.battles.every(b=>!b.estimates.length));}});
test('different report turns and removed reports do not validate a coordinated plan',()=>{const p=plan();p.sets[1].reportTurn=1;assert.match(messages(analyze(p)),/does not match/);p.sets[1].reportTurn=2;assert.match(messages(analyze(p,[report(1)])),/base report is missing/);});
test('enemy orders absent never imply a stationary enemy',()=>{const p=plan();p.reviews={};const a=analyze(p);assert.equal(a.battles[0].estimates.length,0);assert.match(messages(a),/opposing orders are unknown/);p.reviews.BBB={defense:{Army:24,AirF:0,Navy:0},isolated:true,unknownOrders:true,note:'Unknown enemy'};assert.equal(analyze(p).battles[0].estimates.length,0);});
test('new report revisions and new model require review',()=>{const p=plan();p.evidenceKey='b'.repeat(64);assert.match(messages(analyze(p)),/revisions have changed/);p.evidenceKey=key;p.modelVersion='old';assert.match(messages(analyze(p)),/older model/);});
test('report fingerprint covers replacement/removal and ignores future intelligence',async()=>{const rs=reports();const before=await scenarioEvidenceKey(rs,2,[]);assert.equal(before,await scenarioEvidenceKey([...rs,report(1,3)],2,[]));assert.notEqual(before,await scenarioEvidenceKey(rs.slice(0,2),2,[]));rs[0].raw+='\nChanged';assert.notEqual(before,await scenarioEvidenceKey(rs,2,[]));});
test('explicit builds add defense, but cannot finance outgoing units',()=>{const p=opponent(plan(),'ORDERS\n@BBB BA6\nEND');let a=analyze(p);assert.equal(a.battles[0].defense.Army,30);assert.equal(a.battles[0].estimates[1].capture,'none');p.sets[0].text='ORDERS\n@AAA BA6 AC26BBB\nEND';a=analyze(p);assert.match(messages(a),/only 20 are available/);assert.equal(a.battles[0].estimates.length,0);});
test('default proportions follow remaining industry and rule 10 rounding',()=>{const p=opponent(plan(),'ORDERS\n@ BA50 BN25 BF25\nEND');const a=analyze(p);assert.deepEqual(a.battles[0].defense,{Army:27,AirF:1,Navy:2,ABMs:0});assert.equal(a.battles[0].estimates.length,3);});
test('explicit build excludes that default and allocates the remainder sequentially',()=>{const p=opponent(plan(),'ORDERS\n@ BA50 BN25 BF25\n@BBB BA1\nEND');const a=analyze(p);assert.deepEqual(a.battles[0].defense,{Army:25,AirF:2,Navy:3,ABMs:0});});
test('report defaults persist until explicitly zeroed',()=>{const rs=reports();rs[2].defaults='A50 F50';let p=opponent(plan());assert.deepEqual(analyze(p,rs).battles[0].defense,{Army:27,AirF:3,Navy:0,ABMs:0});p=opponent(plan(),'ORDERS\n@ BF0\nEND');assert.equal(analyze(p,rs).battles[0].defense.Army,30);});
test('missing multipliers and same-cycle research leave build-dependent battle incomplete',()=>{const p=opponent(plan(),'ORDERS\n@BBB BA6\nEND'),rs=reports();delete rs[2].multipliers.A;assert.match(messages(analyze(p,rs)),/multiplier is missing/);p.sets[2].text='ORDERS\n@ RA1\n@BBB BA6\nEND';assert.match(messages(analyze(p)),/research may change/);});
test('new industry does not build again in the same cycle',()=>{const p=opponent(plan(),'ORDERS\n@BBB BI6\nEND');assert.equal(analyze(p).battles[0].defense.Army,24);});
test('saved force fractions complete a whole unit when new production is added',()=>{const p=opponent(plan(),'ORDERS\n@BBB BA1\nEND'),rs=reports();for(const r of rs)r.spaces.BBB.values.Army=24.6;rs[2].own.BBB.values.Army=24.6;rs[2].multipliers.A=50;assert.equal(analyze(p,rs).battles[0].defense.Army,25);});
test('movement departs before combat and gifts arrive in the destination garrison',()=>{const p=opponent(plan(),'ORDERS\n@BBB AT5CCC\nEND');p.sets[1].text='ORDERS\n@CCC AT3BBB\nEND';const a=analyze(p);assert.equal(a.battles[0].defense.Army,22);assert.ok(a.battles[0].phases.some(x=>x.includes('arrive before combat')));assert.equal(a.exposures.find(x=>x.code==='CCC')?.defense.Army,12);});
test('suppressed air recovers for defense and unknown suppression blocks automatic defense',()=>{const p=opponent(plan()),rs=reports();for(const r of rs)r.spaces.BBB.suppressed.AirF=5;assert.equal(analyze(p,rs).battles[0].defense.AirF,2);for(const r of rs)delete r.spaces.BBB.suppressed.AirF;assert.match(messages(analyze(p,rs)),/suppressed AirF is unknown/);});
test('suppressed industry recovery is explicitly unsupported',()=>{const p=opponent(plan()),rs=reports();for(const r of rs)r.spaces.BBB.suppressed.Industry=4;assert.match(messages(analyze(p,rs)),/Industry recovery/);assert.equal(analyze(p,rs).battles[0].estimates.length,0);});
test('standing orders require review and active commands cannot be bypassed by the checkbox',()=>{const p=plan();p.sets[0].standingReviewed=false;assert.match(messages(analyze(p)),/review the base report/);p.sets[0].standingReviewed=true;p.sets[0].text='ORDERS\n@AAA AC20BBB /1/BA999\nEND';assert.match(messages(analyze(p)),/active standing orders/);assert.equal(analyze(p).battles[0].estimates.length,0);});
test('persisted standing orders are detected, cancellations work, historical echoes are not proposals',()=>{const rs=reports(),p=plan();rs[0].spaces.AAA.raw+=' /1/AB5BBB';assert.equal(analyze(p,rs).battles[0].estimates.length,0);p.sets[0].text='ORDERS\n@AAA AC20BBB /1/\nEND';assert.equal(analyze(p,rs).battles[0].estimates.length,3);rs[0].orderEcho='@AAA /1/AB999BBB';const clean=reports();clean[0].orderEcho=rs[0].orderEcho;assert.equal(analyze(plan(),clean).battles[0].estimates.length,3);});
test('unsupported combat roles block the affected battle, even with reviewed assumptions',()=>{const p=plan();p.sets[0].text='ORDERS\n@AAA AC20BBB MF1BBB\nEND';const a=analyze(p);assert.match(messages(a),/combat role/);assert.equal(a.battles[0].estimates.length,0);});
test('crossing attacks and returning forces are flagged as connected dependencies',()=>{const p=opponent(plan(),'ORDERS\n@BBB AC20AAA\nEND');p.reviews.AAA={defense:{},isolated:true,unknownOrders:false,note:''};const a=analyze(p);assert.match(messages(a),/border fighting, returns, or counterattacks/);assert.ok(a.battles.every(b=>!b.estimates.length));});
test('new hostility between cooperating attackers is applied before estimation',()=>{const p=plan();p.sets[0].text='ORDERS\n@ 2E\n@AAA AC20BBB\nEND';assert.match(messages(analyze(p)),/another attacker an enemy/);assert.equal(analyze(p).battles[0].estimates.length,0);});
test('new neutral declaration replaces report hostility',()=>{const rs=reports(),p=plan();rs[0].diplomacy.enemies=[2];p.sets[0].text='ORDERS\n@ 2N\n@AAA AC20BBB\nEND';assert.equal(analyze(p,rs).battles[0].estimates.length,3);});
test('ambiguous repeated player declarations do not silently choose an outcome',()=>{const p=plan();p.sets[0].text='ORDERS\n@ 2E 2N\n@AAA AC20BBB\nEND';assert.match(messages(analyze(p)),/resolve repeated or conflicting/);assert.equal(analyze(p).battles[0].estimates.length,0);});
test('unverified canal transfers block their destination defense',()=>{const p=opponent(plan()),rs=reports();rs[0].own.WXX={code:'WXX',kind:'sea',values:{Army:5,Navy:5,AirF:0}};p.sets[0].text='ORDERS\n@AAA AC20BBB\n@WXX NT2BBB\nEND';const a=analyzeTurnPlan(p,rs,'COORD-DEMO',{...atlas,WXX:{...atlas.WXX,surface:[]}},key);assert.match(messages(a),/conditional canal access/);assert.equal(a.battles[0].estimates.length,0);});
test('current source ownership and force strength cannot be borrowed from older intelligence',()=>{const p=plan();p.sets=p.sets.filter(s=>s.player!==2);p.sets[0].text='ORDERS\n@AAA AC20BBB\nEND';const rs=[report(1),report(2,1)];delete rs[0].spaces.BBB;const a=analyze(p,rs);assert.equal(a.battles[0].estimates.length,0);assert.match(messages(a),/current ownership|historical/);});
test('specified threats test home defense and never masquerade as received orders',()=>{const p=plan();p.sets=[{player:1,reportTurn:2,text:'ORDERS\n@AAA AT15CCC\nEND',standingReviewed:true}];p.threats=[{id:'t',player:3,source:'BBB',target:'AAA',role:'conquer',quantity:12}];p.reviews.AAA={defense:{},isolated:true,unknownOrders:false,note:''};const a=analyze(p);assert.equal(a.battles[0].defense.Army,5);assert.equal(a.battles[0].estimates[1].capture,'estimated');assert.equal(a.battles[0].conditional,true);assert.match(a.battles[0].warnings.join(' '),/not submitted orders/);});
test('a player cannot provide both a proposed order set and hypothetical attack allocations',()=>{const p=opponent(plan());p.threats=[{id:'t',player:3,source:'BBB',target:'AAA',role:'conquer',quantity:12}];assert.match(messages(analyze(p)),/not both/);});
test('source conflicts require selection and cannot assign another player’s forces',()=>{const rs=reports(),p=plan();rs[1].spaces.AAA.values.Army=30;assert.equal(analyze(p,rs).battles[0].estimates.length,0);p.choices.AAA='1:2';assert.equal(analyze(p,rs).battles[0].estimates.length,3);rs[1].spaces.AAA.owner=2;p.choices.AAA='2:2';assert.match(messages(analyze(p,rs)),/does not establish Player 1/);});
test('quantity preview changes estimate and reruns budgets without editing originals',()=>{const p=plan(),original=JSON.stringify(p),a=analyze(p);const preview=previewQuantity(p,a.orders[0],10);assert.equal(analyze(preview).battles[0].estimates[1].capture,'none');assert.equal(JSON.stringify(p),original);const tooMany=previewQuantity(p,a.orders[0],21);assert.match(messages(analyze(tooMany)),/only 20 are available/);assert.throws(()=>previewQuantity(p,a.orders[0],1.5));});
test('remaining defense is not labeled safe without an incoming threat',()=>{const a=analyze();assert.equal(a.exposures.find(e=>e.code==='AAA')?.defense.Army,0);assert.match(messages(a),/not a safety guarantee/);});
test('empty input is missing, while explicit ORDERS END is an intentional proposal',()=>{const p=opponent(plan(),'');assert.match(messages(analyze(p)),/missing input|enter proposed orders/);p.sets[2].text='ORDERS\nEND';assert.equal(analyze(p).battles[0].estimates.length,3);});
test('plan persistence round-trips through cloud decode and leaves ordinary drafts independent',()=>{const rs=reports(),p=plan();const state:Workspace={version:1,selectedId:'c',campaigns:[{id:'c',name:'Fictional',game:'COORD-DEMO',player:1,reports:[{filename:rs[0].filename,text:rs[0].raw}],alliedReports:rs.slice(1).map(r=>({filename:r.filename,text:r.raw})),orderDrafts:[{baseTurn:2,text:'ORDERS\nEND',updatedAt:'2026-10-10T00:00:00Z'}]}]};const saved=saveTurnPlan(state,'c',p);assert.deepEqual(decodeWorkspace(JSON.stringify(saved)).campaigns[0].turnPlans,[p]);assert.deepEqual(validateCloudSave({workspace:saved,revision:0}).workspace.campaigns[0].turnPlans,[p]);assert.deepEqual(saved.campaigns[0].orderDrafts,state.campaigns[0].orderDrafts);assert.equal(state.campaigns[0].turnPlans,undefined);assert.equal(removeTurnPlan(saved,'c',p.id).campaigns[0].turnPlans?.length,0);const merged=mergeLocalWorkspace(state,saved);assert.deepEqual(merged.campaigns[0].turnPlans,[p]);const conflict=structuredClone(saved);conflict.campaigns[0].turnPlans![0].name='Different';assert.throws(()=>mergeLocalWorkspace(saved,conflict),/Conflicting coordinated/);});
test('invalid plans cannot enter workspace storage',()=>{const p=plan();for(const mutate of [(x:TurnPlan)=>x.sets.push({...x.sets[0]}),(x:TurnPlan)=>x.orderTurn=99,(x:TurnPlan)=>x.sets[0].text='x'.repeat(100001),(x:TurnPlan)=>x.reviews.BBB.defense.Army=-1,(x:TurnPlan)=>x.threats.push({id:'bad',player:3,source:'BBB',target:'AAA',role:'armySupport',quantity:1})]){const copy=structuredClone(p);mutate(copy);assert.throws(()=>validateTurnPlans([copy]));}assert.throws(()=>validateTurnPlans(Array(51).fill(p)));});
