"use client";
import {useEffect,useMemo,useState} from 'react';
import {parseReport} from '../lib/wwbp/parser';
import type {Campaign,Geography,Report} from '../lib/wwbp/types';
import {holderLabel} from '../lib/combined-intelligence';
import {roles,defenseFields,MODEL_VERSION,type BattleScenario,type BattleRole,type Commitment} from '../lib/scenario-types';
import {newScenario,scenarioEvidenceKey} from '../lib/scenario-storage';
import {analyzeBattle,forceOrigin,roleProblem,displayNumber as num,type BattleEstimate} from '../lib/battle-scenarios';

type Props={campaign:Campaign;referenceTurn:number|null;atlas:Record<string,Geography>;busy:boolean;onSave:(s:BattleScenario)=>Promise<void>;onRemove:(id:string)=>Promise<void>;onDirty:(dirty:boolean)=>void};
export default function BattleScenarios({campaign,referenceTurn,atlas,busy,onSave,onRemove,onDirty}:Props){
 const reports=useMemo(()=>[...campaign.reports,...(campaign.alliedReports||[])].map(r=>parseReport(r.text,r.filename)),[campaign.reports,campaign.alliedReports]);
 const saved=campaign.battleScenarios||[];
 const [draft,setDraft]=useState<BattleScenario|null>(null),[dirty,setDirty]=useState(false),[message,setMessage]=useState(''),[deleting,setDeleting]=useState(false);
 const [comparison,setComparison]=useState('');
 const turns=[...new Set(reports.map(r=>r.turn))].sort((a,b)=>b-a);
 const targets=Object.keys(atlas).filter(code=>!code.startsWith('W')).sort((a,b)=>atlas[a].name.localeCompare(atlas[b].name));
 useEffect(()=>{onDirty(dirty);return()=>onDirty(false);},[dirty,onDirty]);
 useEffect(()=>{if(!dirty)return;const stop=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',stop);return()=>window.removeEventListener('beforeunload',stop);},[dirty]);
 const change=(next:BattleScenario)=>{setDraft(next);setDirty(true);setMessage('');};
 function start(){const turn=referenceTurn??turns[0];if(turn===undefined)return;change(newScenario(turn,targets.find(code=>reports.some(r=>r.spaces[code]&&r.spaces[code].owner!==campaign.player))||targets[0]));setComparison('');setDeleting(false);}
 async function save(){if(!draft)return;setMessage('');try{const next={...draft,name:draft.name.trim()||'Land scenario',updatedAt:new Date().toISOString()};await onSave(next);setDraft(next);setDirty(false);setMessage('Scenario saved. Reports and order drafts are unchanged.');}catch(e){setMessage((e as Error).message);}}
 const compare=saved.find(s=>s.id===comparison&&s.id!==draft?.id&&s.target===draft?.target&&s.baseTurn===draft?.baseTurn);
 return <section className="battle-scenarios" aria-labelledby="scenario-title">
  <div><p className="eyebrow">{campaign.game} · Analysis</p><h1 id="scenario-title">Attack & defense scenarios</h1><p>Plan one land engagement using combined intelligence. Compare commitments, inspect each combat stage, and save alternatives separately from your orders.</p></div>
  <div className="scenario-library"><label>Saved scenario<select name="saved-scenario" disabled={dirty||busy} value={draft&&saved.some(s=>s.id===draft.id)?draft.id:''} onChange={e=>{setDraft(saved.find(s=>s.id===e.target.value)||null);setComparison('');setMessage('');setDeleting(false);}}><option value="">Choose a saved scenario</option>{saved.map(s=><option key={s.id} value={s.id}>{s.name} · {s.target} · Turn {s.orderTurn}</option>)}</select></label><button type="button" disabled={!turns.length||dirty||busy} onClick={start}>New scenario</button></div>
  {!turns.length&&<p>Import a report to start a scenario.</p>}
  {message&&<p role="status" className="scenario-note">{message}</p>}
  {draft?<>
   <div className="scenario-save"><p>{dirty?'Unsaved scenario changes.':'Saved scenario.'} Save or discard before switching scenarios or campaigns.</p><div className="actions"><button type="button" className="primary" disabled={busy||!dirty} onClick={()=>void save()}>Save scenario</button><button type="button" disabled={busy||!dirty} onClick={()=>{setDraft(saved.find(s=>s.id===draft.id)||null);setDirty(false);setMessage('Changes discarded.');}}>Discard changes</button><button type="button" disabled={busy||dirty} onClick={()=>{change({...structuredClone(draft),id:crypto.randomUUID(),name:`${draft.name.slice(0,60)} · alternative`});setComparison(draft.id);}}>Copy as alternative</button>{saved.some(s=>s.id===draft.id)&&<button type="button" disabled={busy||dirty} onClick={()=>setDeleting(!deleting)}>Delete scenario</button>}</div></div>
   {deleting&&<div className="scenario-note"><p>Delete “{draft.name}”? The saved scenario will be removed.</p><div className="actions"><button type="button" disabled={busy} onClick={async()=>{try{await onRemove(draft.id);setDraft(null);setDeleting(false);setMessage('Scenario deleted.');}catch(e){setMessage((e as Error).message);}}}>Confirm deletion</button><button type="button" onClick={()=>setDeleting(false)}>Cancel</button></div></div>}
   <fieldset disabled={busy} className="scenario-editor"><ScenarioEditor scenario={draft} reports={reports} game={campaign.game} atlas={atlas} turns={turns} targets={targets} change={change}/></fieldset>
   <section className="scenario-comparison"><h2>Compare an alternative</h2><p>Choose a saved plan for the same target and base turn. Each result uses that plan’s own sources and assumptions.</p><label>Compare with<select name="scenario-comparison" value={compare?.id||''} onChange={e=>setComparison(e.target.value)}><option value="">No comparison selected</option>{saved.filter(s=>s.id!==draft.id&&s.target===draft.target&&s.baseTurn===draft.baseTurn).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>{compare&&<ReadOnlyComparison scenario={compare} reports={reports} game={campaign.game} atlas={atlas}/>}</section>
  </>:!!turns.length&&<p className="allied-empty">Create a scenario or open a saved plan. No forces are committed until you select them.</p>}
 </section>;
}

function useEvidence(s:BattleScenario,reports:Report[]){
 const input=useMemo(()=>({reports,turn:s.baseTurn,excluded:s.excludedPlayers}),[reports,s.baseTurn,s.excludedPlayers]);
 const [result,setResult]=useState<{input:typeof input;key:string;error:string}|null>(null);
 useEffect(()=>{let cancelled=false;scenarioEvidenceKey(input.reports,input.turn,input.excluded).then(key=>{if(!cancelled)setResult({input,key,error:''});}).catch(()=>{if(!cancelled)setResult({input,key:'',error:'Could not verify source revisions. Reload before analyzing.'});});return()=>{cancelled=true;};},[input]);
 return result?.input===input?result:{key:'',error:''};
}
function ScenarioEditor({scenario:s,reports,game,atlas,turns,targets,change}:{scenario:BattleScenario;reports:Report[];game:string;atlas:Record<string,Geography>;turns:number[];targets:string[];change:(s:BattleScenario)=>void}){
 const evidence=useEvidence(s,reports);
 const result=analyzeBattle(s,reports,game,atlas,evidence.key);
 const [source,setSource]=useState(''),[role,setRole]=useState<BattleRole>('conquer'),[quantity,setQuantity]=useState('1'),[hypothetical,setHypothetical]=useState(false),[hypCode,setHypCode]=useState(''),[hypPlayer,setHypPlayer]=useState('2'),[hypKind,setHypKind]=useState<'occupied'|'minor'|'sea'>('occupied'),[addError,setAddError]=useState('');
 const [search,setSearch]=useState('');
 const patch=(value:Partial<BattleScenario>)=>change({...s,...value});
 const target=result.rows.find(r=>r.group.id===s.target);
 const relevant=result.rows.filter(r=>r.group.id===s.target||s.commitments.some(c=>!c.hypothetical&&c.groupId===r.group.id));
 const options=result.rows.filter(r=>(r.holder?.player!=null||r.conflicts.length>0)&&!r.historical&&r.group.code!==s.target&&`${r.group.code} ${atlas[r.group.code]?.name||''} Player ${r.holder?.player??''}`.toLowerCase().includes(search.toLowerCase()));
 const selected=options.find(r=>r.group.id===source)||options[0];
 const origin=hypothetical?{code:hypCode,kind:hypCode.startsWith('W')?'sea':hypKind}:selected?.holder?{code:selected.group.code,kind:selected.holder.kind}:null;
 const rangeProblem=origin?roleProblem(origin.code,origin.kind,role,s.target,atlas):'Choose a source.';
 function add(){
  const n=Number(quantity),player=Number(hypPlayer);
  if(!Number.isSafeInteger(n)||n<1||n>1_000_000){setAddError('Enter 1–1,000,000 whole units.');return;}
  if(rangeProblem){setAddError(rangeProblem);return;}
  if(hypothetical&&(!Number.isSafeInteger(player)||player<1||player>999)){setAddError('Enter a player from 1 to 999.');return;}
  const id=crypto.randomUUID();const c:Commitment={id,groupId:hypothetical?`hyp:${id}`:selected!.group.id,role,quantity:n,...(hypothetical?{hypothetical:{code:hypCode,player,kind:hypCode.startsWith('W')?'sea' as const:hypKind}}:{})};
  patch({commitments:[...s.commitments,c]});setAddError('');
 }
 const reporters=[...new Set(reports.filter(r=>r.turn<=s.baseTurn).map(r=>r.player))].sort((a,b)=>a-b);
 return <>
  <div className="scenario-grid"><label>Scenario name<input name="scenario-name" maxLength={80} value={s.name} onChange={e=>patch({name:e.target.value})}/></label><label>Planning goal<select name="scenario-mode" value={s.mode} onChange={e=>patch({mode:e.target.value as BattleScenario['mode']})}><option value="attack">Attack / capture a country</option><option value="defense">Defend against a specified attack</option></select></label><label>Base intelligence turn<select name="scenario-turn" value={s.baseTurn} onChange={e=>patch({baseTurn:+e.target.value,orderTurn:+e.target.value+1,evidenceKey:'',choices:{},assumptions:{precombat:false,isolated:false}})}>{[...new Set([...turns,s.baseTurn])].sort((a,b)=>b-a).map(t=><option key={t} value={t}>Turn {t}</option>)}</select></label><label>Target country<select name="scenario-target" value={s.target} onChange={e=>patch({target:e.target.value,defense:{},targetHolder:undefined,assumptions:{precombat:false,isolated:false}})}>{targets.map(code=><option key={code} value={code}>{atlas[code].name} · {code}</option>)}</select></label></div>
  <p className="scenario-note">{game} · Base report turn {s.baseTurn} → intended order turn {s.orderTurn}. {s.mode==='defense'?'Specify the attack, then vary the garrison and supporting forces to see what holds.':'Select only the forces you intend to send; in-range forces are not committed automatically.'}</p>
  <div className="scenario-live"><p role="status">{result.estimates[1]?.outcome||"Incomplete — review the inputs below."}</p><a href="#scenario-forces">Edit commitments</a><a href="#scenario-result">View estimate and progression</a></div>
  <details><summary>Intelligence sources and revisions</summary><div className="scenario-checks">{reporters.map(player=><label key={player}><input type="checkbox" checked={!s.excludedPlayers.includes(player)} onChange={e=>patch({excludedPlayers:e.target.checked?s.excludedPlayers.filter(p=>p!==player):[...s.excludedPlayers,player]})}/><span>Use reports from Player {player}</span></label>)}</div><p>Scenarios keep their own source choices. Historical forces cannot be allocated; future reports are excluded.</p></details>
  {evidence.error&&<p role="alert">{evidence.error}</p>}
  <div className="scenario-evidence-status"><p>{!evidence.key?'Checking source revisions…':s.evidenceKey===evidence.key&&s.modelVersion===MODEL_VERSION?'Source revisions match this scenario.':'Review needed: new, removed, or changed intelligence, or a new scenario.'}</p><button type="button" disabled={!evidence.key} onClick={()=>patch({evidenceKey:evidence.key,modelVersion:MODEL_VERSION,choices:{},assumptions:{precombat:false,isolated:false}})}>Use current intelligence</button></div>
  <details open className="scenario-section"><summary>1. Target defense before combat</summary><p>{holderLabel(s.targetHolder||target?.holder||null)}. Blank fields use current resolved intelligence. Enter a value to make an explicit assumption about the defense after movement, builds, and recovery, before selected support arrives.</p><div className="scenario-grid">{defenseFields.map(field=><label key={field}>{field}<input type="number" name={`defense-${field}`} aria-label={`Target ${field}`} min={0} max={1000000} step={1} placeholder={target&&!target.historical&&(!target.conflicts.length||target.chosen)&&target.values[field]!==undefined?`Reported: ${Math.floor(target.values[field]!)}`:'Unknown — enter assumption'} value={s.defense[field]??''} onChange={e=>{const defense={...s.defense};if(e.target.value==='')delete defense[field];else defense[field]=Number(e.target.value);patch({defense});}}/>{s.defense[field]!==undefined?<small>Hypothetical pre-combat value</small>:<small>{target?.historical?`Historical turn ${target.group.turn}; excluded`:`${target?.suppressed[field]===undefined?'Suppression not reported':`${num(target.suppressed[field]!)} suppressed, excluded from active value`}`}</small>}</label>)}</div>
   <details><summary>Assume different ownership or control</summary><label className="scenario-check"><input type="checkbox" checked={!!s.targetHolder} onChange={e=>patch({targetHolder:e.target.checked?{kind:'occupied',player:target?.holder?.player||2}:undefined})}/><span>Use hypothetical target ownership</span></label>{s.targetHolder&&<div className="scenario-grid"><label>Ownership type<select value={s.targetHolder.kind} onChange={e=>patch({targetHolder:{kind:e.target.value as 'occupied'|'minor',player:s.targetHolder!.player||2}})}><option value="occupied">Occupied</option><option value="minor">Minor</option></select></label><label>Owner/controller player (0 = unassigned minor)<input type="number" min={s.targetHolder.kind==='minor'?0:1} max={999} value={s.targetHolder.player??0} onChange={e=>patch({targetHolder:{...s.targetHolder!,player:Number(e.target.value)||null}})}/></label></div>}</details>
  </details>
  <details open className="scenario-section" id="scenario-forces"><summary>2. Committed forces</summary><p>Conquer can capture; bombard returns home; support defends the target. Missiles and air attacks in this version target army. Local defenders are already counted above.</p>
   <div className="scenario-add"><label className="scenario-check"><input name="hypothetical-source" type="checkbox" checked={hypothetical} onChange={e=>setHypothetical(e.target.checked)}/><span>Enter hypothetical forces (enemy forces or reinforcements)</span></label>
    <div className="scenario-grid">{hypothetical?<><label>Hypothetical source<select name="hypothetical-location" value={hypCode} onChange={e=>setHypCode(e.target.value)}><option value="">Choose a location</option>{Object.keys(atlas).filter(c=>c!==s.target).sort().map(c=><option key={c} value={c}>{atlas[c].name} · {c}</option>)}</select></label><label>Player<input name="hypothetical-player" type="number" min={1} max={999} value={hypPlayer} onChange={e=>setHypPlayer(e.target.value)}/></label>{!hypCode.startsWith('W')&&<label>Source type<select name="hypothetical-kind" value={hypKind} onChange={e=>setHypKind(e.target.value as typeof hypKind)}><option value="occupied">Occupied country</option><option value="minor">Controlled minor</option></select></label>}</>:<><label>Find a source<input type="search" name="scenario-source-search" placeholder="Country, sea, or Player 2" value={search} onChange={e=>setSearch(e.target.value)}/></label><label>Reported source<select name="scenario-source" value={selected?.group.id||''} onChange={e=>setSource(e.target.value)}>{!options.length&&<option value="">No current sources match</option>}{options.map(r=><option key={r.group.id} value={r.group.id}>{atlas[r.group.code]?.name||r.group.code} · {r.group.code} · P{r.holder?.player??'?'}{r.holder?.kind==='minor'?' · minor':''}{r.conflicts.length&&!r.chosen?' · conflict':''}</option>)}</select></label></>}
    <label>Role<select name="scenario-role" value={role} onChange={e=>setRole(e.target.value as BattleRole)}>{Object.entries(roles).map(([key,r])=><option key={key} value={key}>{r.side==='attack'?'Attack':'Defense'} · {r.label}</option>)}</select></label><label>Whole units<input name="scenario-quantity" type="number" min={1} max={1000000} step={1} value={quantity} onChange={e=>setQuantity(e.target.value)}/></label></div>
    {!hypothetical&&selected&&<p>{roles[role].field}: {selected.values[roles[role].field]===undefined?'unknown':`${Math.floor(selected.values[roles[role].field]!)} available before commitments`}. Source turn {selected.group.turn}; {selected.group.candidates.length} report(s). Fractions and suppressed units are excluded.</p>}
    {!hypothetical&&selected&&selected.conflicts.length>0&&<label>Resolve source disagreement<select name="candidate-source-choice" value={s.choices[selected.group.id]||''} onChange={e=>{const choices={...s.choices};if(e.target.value)choices[selected.group.id]=e.target.value;else delete choices[selected.group.id];patch({choices});}}><option value="">Unresolved: {selected.conflicts.join(', ')}</option>{selected.group.candidates.map(o=><option key={o.source.id} value={o.source.id}>P{o.source.player} · Turn {o.source.turn} · {o.source.filename}</option>)}</select></label>}
    <p>{rangeProblem||'Source and role are in range for this target.'}</p>{addError&&<p role="alert" className="import-error">{addError}</p>}<button type="button" disabled={!!rangeProblem||s.commitments.length>=100} onClick={add}>Add commitment</button>
   </div>
   {s.commitments.length?<div className="table-scroll scenario-table" tabIndex={0} role="region" aria-label="Committed forces"><table><thead><tr><th>Side / source</th><th>Role</th><th>Units</th><th>Evidence</th><th>Action</th></tr></thead><tbody>{s.commitments.map(c=>{const o=forceOrigin(c,result.rows);return <tr key={c.id}><th scope="row">{roles[c.role].side==='attack'?'Attacking':'Defending'} · {o?.code||c.groupId} · P{o?.player??'?'}</th><td>{roles[c.role].label}</td><td><input type="number" min={1} max={1000000} step={1} aria-label={`Units ${o?.code||c.groupId} ${roles[c.role].label}`} value={c.quantity} onChange={e=>patch({commitments:s.commitments.map(x=>x.id===c.id?{...x,quantity:Number(e.target.value)}:x)})}/></td><td>{c.hypothetical?'Hypothetical':`Reported turn ${o?.row?.group.turn??'missing'}`}</td><td><button type="button" onClick={()=>patch({commitments:s.commitments.filter(x=>x.id!==c.id)})}>Remove</button></td></tr>;})}</tbody></table></div>:<p>No forces committed.</p>}
  </details>
  <details className="scenario-section"><summary>Evidence and conflict choices for selected locations</summary>{relevant.map(row=><article className="scenario-source" key={row.group.id}><h3>{row.group.id} · {holderLabel(row.holder)} · Turn {row.group.turn}</h3>{!!row.conflicts.length&&<label>Choose source for {row.group.id}<select aria-label={`Scenario source choice ${row.group.id}`} value={s.choices[row.group.id]||''} onChange={e=>{const choices={...s.choices};if(e.target.value)choices[row.group.id]=e.target.value;else delete choices[row.group.id];patch({choices});}}><option value="">Unresolved: {row.conflicts.join(', ')}</option>{row.group.candidates.map(o=><option key={o.source.id} value={o.source.id}>P{o.source.player} · Turn {o.source.turn} · {o.source.filename}</option>)}</select></label>}{row.group.candidates.map(o=><details key={o.source.id}><summary>P{o.source.player} · Turn {o.source.turn} · {o.source.filename}</summary><pre>{o.record}</pre></details>)}</article>)}</details>
  <details open className="scenario-section"><summary>3. Assumptions</summary><div className="scenario-checks"><label><input type="checkbox" name="assumption-precombat" checked={s.assumptions.precombat} onChange={e=>patch({assumptions:{...s.assumptions,precombat:e.target.checked}})}/><span>I have accounted for movement, builds, standing orders, and recovering air in the target values. Selected supporting forces are additional; outgoing forces are available before builds.</span></label><label><input type="checkbox" name="assumption-isolated" checked={s.assumptions.isolated} onChange={e=>patch({assumptions:{...s.assumptions,isolated:e.target.checked}})}/><span>Assume an isolated standard-rules engagement: no crossing attacks, counterattacks, hostile attackers fighting each other, diplomatic combat penalties, or other battles affecting these forces.</span></label></div><label>Notes and assumptions<textarea name="scenario-notes" rows={3} maxLength={4000} value={s.notes} onChange={e=>patch({notes:e.target.value})} placeholder="For example: defender builds 4 army; no reinforcements beyond those listed."/></label><p>Air/missile raids on industry or air bases, air attacks on navy, sea battles, and connected operations are outside this model. If they affect this engagement, leave the isolated assumption unchecked.</p></details>
  <BattleResult result={result} mode={s.mode}/>
 </>;
}

function ReadOnlyComparison({scenario,reports,game,atlas}:{scenario:BattleScenario;reports:Report[];game:string;atlas:Record<string,Geography>}){
 const evidence=useEvidence(scenario,reports);const result=analyzeBattle(scenario,reports,game,atlas,evidence.key);
 return <div className="scenario-comparison-result"><h3>{scenario.name}</h3><p>{scenario.commitments.length} commitments · {scenario.mode} · {scenario.notes||'No additional notes.'}</p><BattleResult result={result} mode={scenario.mode} compact/></div>;
}
function BattleResult({result,mode,compact=false}:{result:ReturnType<typeof analyzeBattle>;mode:BattleScenario['mode'];compact?:boolean}){
 const estimate=result.estimates[1];
 return <section className="scenario-result" id={compact?undefined:'scenario-result'} aria-label={compact?'Comparison estimate':'Scenario estimate'}><h2>{compact?'Saved alternative estimate':'Estimated outcome'}</h2>{result.errors.length?<div className="import-error" role="status"><h3>Incomplete — no outcome estimated</h3><ul>{result.errors.map(e=><li key={e}>{e}</li>)}</ul></div>:estimate&&<><p className="scenario-outcome" role="status">{estimate.outcome}</p><p>{mode==='defense'?'This tests the specified attack against the selected defense. It is not a universal minimum defense.':'Capture needs a surviving eligible conquer group; defeating defenders alone does not occupy the target.'}</p><div className="table-scroll scenario-table" tabIndex={0} role="region" aria-label={compact?'Alternative sensitivity':'Outcome sensitivity'}><table><thead><tr><th>Approximate hit rate</th><th>Outcome</th><th>Attacking army left</th><th>Defending army left</th><th>Conquering army left</th></tr></thead><tbody>{result.estimates.map(e=><tr key={e.rate}><th scope="row">{e.rate===0.5?'Rulebook approximation':e.rate===0.25?'Lower hits':'Higher hits'} · {e.rate}</th><td>{e.outcome}</td><td>{num(e.attackArmy)}</td><td>{num(e.defenseArmy)}</td><td>{num(e.conquer)}</td></tr>)}</tbody></table></div><p>Sensitivity changes the approximate air/naval hit rate from 0.25 to 0.75. The rulebook’s central value is about 0.5; these are illustrative assumptions, not calibrated odds.</p>{!compact&&<EstimateDetails estimate={estimate}/>}</>}{!compact&&<details><summary>Model limits and assumptions</summary><p>Model {MODEL_VERSION}. Rulebook 4C–4G, 5F.4 and sequence 9. Army losses use loser² ÷ winner. Air/naval losses are approximate; air-combat losses are shared equally and group losses proportionally. Estimates stop at initial land capture, before sea combat and returns.</p><ul>{result.warnings.map(w=><li key={w}>{w}</li>)}</ul></details>}</section>;
}
function EstimateDetails({estimate:e}:{estimate:BattleEstimate}){
 return <><details open><summary>Combat progression</summary><ol className="scenario-stages">{e.stages.map(stage=><li key={stage.name}><h3>{stage.name}</h3><p>{stage.detail}</p></li>)}</ol></details><details><summary>Estimated surviving commitments</summary><p>Fractional values are expectations. Loss allocation is approximate; surviving support and bombard forces return after this battle, subject to later combat.</p><div className="table-scroll scenario-table"><table><thead><tr><th>Source</th><th>Role</th><th>Committed</th><th>Lost / expended</th><th>Remaining</th></tr></thead><tbody>{e.survivors.map(g=><tr key={g.force.id}><th scope="row">{g.force.code} · P{g.force.player}{g.force.hypothetical?' · hypothetical':''}</th><td>{roles[g.force.role].label}</td><td>{num(g.force.quantity)}</td><td>{num(g.force.quantity-g.remaining)}</td><td>{num(g.remaining)}</td></tr>)}</tbody></table></div><p>Defender pool remaining (local + support): {num(e.defenseArmy)} army, {num(e.defenseAir)} air, {num(e.defenseNavy)} navy. Attacking air remaining: {num(e.attackAir)}; attacking navy: {num(e.attackNavy)}.</p></details></>;
}
