"use client";
import {useEffect,useMemo,useRef,useState} from 'react';
import atlasData from '../data/atlas.json';
import {parseReport,metrics,compare} from '../lib/wwbp/parser';
import {fields,type Campaign,type Geography,type RawReport,type Report,type Workspace} from '../lib/wwbp/types';
import {browserRepository,createCampaign,emptyWorkspace,importReports} from '../lib/workspace';
import {demoWorkspace} from '../lib/demo';
import {pastedReport} from '../lib/pasted-report';
import {browserClient} from '../lib/supabase/browser';
import {loadCloud,saveCloud} from '../lib/cloud-repository';
import {mergeLocalWorkspace} from '../lib/cloud-validation';
import OperationsMap from './operations-map';
import ForcesInRange from './forces-in-range';
import Multipliers from './multipliers';
import {mapChanges} from '../lib/map-changes';
import CampaignManager from './campaign-manager';
import {manageCampaign} from '../lib/campaign-management';
const atlas:Record<string,Geography>=atlasData;
const num=(n:number|undefined)=>n==null?'—':n.toLocaleString('en-US',{maximumFractionDigits:2});
const name=(code:string)=>atlas[code]?.name||code;
function download(filename:string,text:string,type='application/json'){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export default function CampaignRoom({account}:{account?:{id:string;email:string}}){
 const revision=useRef(0),saving=useRef(false);
 const [signedOut,setSignedOut]=useState(false),[hasLocal,setHasLocal]=useState(false),[transferError,setTransferError]=useState('');
 const transferDialog=useRef<HTMLDialogElement>(null);
 const [state,setState]=useState<Workspace>(emptyWorkspace),[ready,setReady]=useState(false),[loadError,setLoadError]=useState(false),[message,setMessage]=useState(''),[demo,setDemo]=useState(false),[adding,setAdding]=useState(false),[pending,setPending]=useState<RawReport[]>([]),[busy,setBusy]=useState(false);
 const [pasted,setPasted]=useState(''),[importError,setImportError]=useState('');
 const pasteDialog=useRef<HTMLDialogElement>(null);
 const input=useRef<HTMLInputElement>(null);const dialog=useRef<HTMLDialogElement>(null);const importTarget=useRef('');
 useEffect(()=>{let active=true;async function load(){try{if(account){const result=await loadCloud();if(!active)return;revision.current=result.revision;setState(result.workspace);try{setHasLocal(browserRepository(localStorage).load().campaigns.length>0);}catch{/* Local data remains untouched. */}}else setState(browserRepository(localStorage).load());}catch(e){if(active){setMessage(`Could not load campaigns: ${(e as Error).message} Existing data has not been overwritten.`);setLoadError(true);}}finally{if(active)setReady(true);}}void load();
 const subscription=account?browserClient().auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_OUT'||(session&&session.user.id!==account.id)){setSignedOut(true);window.location.replace('/login');}}).data.subscription:null;
 return()=>{active=false;subscription?.unsubscribe();};},[account?.id]);
 const campaign=state.campaigns.find(c=>c.id===state.selectedId);
 async function commit(next:Workspace){if(loadError)throw Error('Reload your campaigns before making changes.');if(saving.current)throw Error('Wait for the current save to finish.');saving.current=true;setBusy(true);try{if(!demo){if(account)revision.current=await saveCloud(next,revision.current);else browserRepository(localStorage).save(next);}setState(next);}finally{saving.current=false;setBusy(false);}}
 async function act(fn:()=>void|Promise<void>){try{await fn();}catch(e){setMessage((e as Error).message);}}
 async function reloadCloud(){setBusy(true);try{const result=await loadCloud();revision.current=result.revision;setState(result.workspace);setLoadError(false);setDemo(false);setMessage('Loaded the latest cloud campaigns.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 async function signOut(){setBusy(true);try{const {error}=await browserClient().auth.signOut();if(error)throw error;setSignedOut(true);window.location.replace('/login');}catch{setMessage('Sign-out failed. Please try again.');setBusy(false);}}

 function add(form:FormData){act(async()=>{await commit(createCampaign(state,String(form.get('name')),String(form.get('game')),Number(form.get('player')),crypto.randomUUID()));setAdding(false);setMessage('Campaign created. Import its reports to begin.');});}
 function review(raw:RawReport[],id:string){importReports(state,id,raw);importTarget.current=id;setPending(raw);setImportError('');pasteDialog.current?.close();dialog.current?.showModal();}
 function reviewPaste(){if(!campaign)return;try{review([pastedReport(pasted)],campaign.id);}catch(e){setImportError((e as Error).message);}}
 async function preview(files:FileList|null){if(!files?.length||!campaign)return;const id=campaign.id;setBusy(true);try{const raw:RawReport[]=[];for(const f of Array.from(files)){if(f.size>2_000_000)throw Error(`${f.name} is larger than 2 MB.`);raw.push({filename:f.name,text:await f.text()});}review(raw,id);}catch(e){setImportError((e as Error).message);}finally{setBusy(false);if(input.current)input.current.value='';}}
 if(signedOut)return <main className="empty"><p>Signing out…</p></main>;
 return <div className="app-shell"><a className="skip" href="#main">Skip to campaign</a><header className="masthead"><a className="brand" href="/" aria-label="Homepage">WWBP <span>Campaign room</span></a><div className="actions">{account?<><p className="account-email">{account.email}</p><button type="button" disabled={busy} onClick={()=>void signOut()}>Sign out</button></>:<a href="/login">Cloud sign-in</a>}</div></header>
 <main id="main"><div className="notice">{demo?'Demo mode · All game data is fictional and changes are temporary.':account?'Private cloud workspace · Saved to your account. Alliance sharing is not enabled.':'Browser workspace · Reports stay in this browser. Cloud accounts are not configured yet.'}</div>
 <div className="campaign-switch"><label>Campaign<select name="campaign" disabled={!ready||busy||!state.campaigns.length} value={state.selectedId??''} onChange={e=>act(()=>commit({...state,selectedId:e.target.value}))}>{!state.campaigns.length&&<option value="">No campaigns yet</option>}{[false,true].map(archived=>{const campaigns=state.campaigns.filter(c=>!!c.archived===archived);return campaigns.length?<optgroup key={String(archived)} label={archived?'Archived':'Active'}>{campaigns.map(c=><option key={c.id} value={c.id}>{c.name} · {c.game} / P{c.player}</option>)}</optgroup>:null;})}</select></label><button type="button" disabled={!ready||busy||loadError} onClick={()=>setAdding(!adding)}>Add campaign</button>{demo&&<button type="button" onClick={()=>account?void reloadCloud():void act(()=>{setState(browserRepository(localStorage).load());setDemo(false);})}>Exit demo</button>}{campaign&&<CampaignManager key={campaign.id} campaign={campaign} busy={busy||loadError} onChange={change=>commit(manageCampaign(state,campaign.id,change))} onExport={()=>download(`${campaign.game}-campaign.json`,JSON.stringify(campaign,null,2))}/>} {campaign&&<button type="button" disabled={busy||loadError} className="primary" onClick={()=>{setImportError('');pasteDialog.current?.showModal();}}>{busy?'Reading reports…':'Import reports'}</button>}</div>
 {account&&<div className="cloud-tools"><p role="status">{busy?'Saving or loading…':loadError?'Cloud data unavailable.':'Cloud saves enabled.'}</p><button type="button" disabled={busy} onClick={()=>void reloadCloud()}>Reload cloud data</button>{hasLocal&&!demo&&<button type="button" disabled={busy||loadError} onClick={()=>{setTransferError('');transferDialog.current?.showModal();}}>Transfer browser campaigns</button>}</div>}
 {campaign?.archived&&<p className="archive-notice">Archived campaign · Reports remain available. Use Manage campaign to restore it to active games.</p>}
 {message&&<div role="status" className="status">{message}<button type="button" aria-label="Dismiss message" onClick={()=>setMessage('')}>Dismiss</button></div>}
 {adding&&<form className="add-form" onSubmit={e=>{e.preventDefault();add(new FormData(e.currentTarget));}}><h2>Add a campaign</h2><p>Use the game identifier and player number printed at the top of your report.</p><label>Campaign name<input name="name" maxLength={80} placeholder="My X309 campaign"/></label><label>Game identifier<input name="game" required placeholder="WW-X309" maxLength={40}/></label><label>Player number<input name="player" type="number" min={1} max={999} required/></label><div className="actions"><button type="submit" disabled={busy}>Create campaign</button><button type="button" onClick={()=>setAdding(false)}>Cancel</button></div></form>}
 {!ready?<p className="empty">Loading your workspace…</p>:!campaign?<section className="empty"><p className="eyebrow">Your campaign room</p><h1>Every game. Its own intelligence.</h1><p>Add X308, X309, or your next campaign, then import its turn reports. Switch games without mixing their histories.</p><button type="button" onClick={()=>{setState(demoWorkspace());setDemo(true);setMessage('Two fictional campaigns are ready to explore.');}}>Explore the fictional demo</button></section>:<CampaignView key={campaign.id} campaign={campaign} onExport={()=>download(`${campaign.game}-campaign.json`,JSON.stringify(campaign,null,2))}/>}
 <footer><p>World Wide Battle Plan companion · In development.</p><p>Keep original reports as your backup. Alliance sharing is planned.</p></footer></main>
 <dialog ref={transferDialog} aria-labelledby="transfer-title"><h2 id="transfer-title">Transfer browser campaigns?</h2><p>This uploads the campaigns and original report text stored in this browser to {account?.email}. Existing cloud reports are preserved. Conflicting turns stop the transfer; browser originals remain untouched.</p>{transferError&&<p role="alert" className="import-error">{transferError}</p>}<div className="actions"><button type="button" className="primary" disabled={busy} onClick={async()=>{try{await commit(mergeLocalWorkspace(state,browserRepository(localStorage).load()));transferDialog.current?.close();setHasLocal(false);setMessage('Browser campaigns transferred to your account. Local originals were preserved.');}catch(e){setTransferError((e as Error).message);}}}>Transfer to my account</button><button type="button" disabled={busy} onClick={()=>transferDialog.current?.close()}>Cancel</button></div></dialog>
 <dialog ref={pasteDialog} className="paste-dialog" aria-labelledby="paste-title"><h2 id="paste-title">Import a turn report</h2><p>{campaign?.name} · {campaign?.game} · Player {campaign?.player}</p><p id="paste-help">Copy the complete report from the email body, then paste it below. Include the game heading and all report sections.</p><label htmlFor="email-report">Email report</label><textarea id="email-report" name="email-report" aria-describedby="paste-help" value={pasted} onChange={e=>{setPasted(e.target.value);setImportError('');}} placeholder="Paste your turn report here…" spellCheck={false} autoCapitalize="off" autoCorrect="off"/>{importError&&<p role="alert" className="import-error">{importError}</p>}<div className="actions"><button type="button" className="primary" disabled={busy||!pasted.trim()} onClick={reviewPaste}>Review pasted report</button><button type="button" disabled={busy} onClick={()=>input.current?.click()}>{busy?'Reading files…':'Choose text files'}</button><button type="button" disabled={busy} onClick={()=>pasteDialog.current?.close()}>Cancel</button></div><input ref={input} name="reports" type="file" hidden multiple accept=".txt,text/plain" onChange={e=>void preview(e.target.files)}/></dialog>
 <dialog ref={dialog} aria-labelledby="import-title"><h2 id="import-title">Review report import</h2><p>{campaign?.name} · {campaign?.game} · Player {campaign?.player}</p><ul>{pending.map((r,i)=>{const p=parseReport(r.text,r.filename);return <li key={i}>{r.filename} · Turn {p.turn}</li>;})}</ul>{importError&&<p role="alert" className="import-error">{importError}</p>}<p>Matching duplicates will be skipped. Conflicting reports will leave this campaign unchanged.</p><div className="actions"><button type="button" className="primary" disabled={busy} onClick={async()=>{try{const result=importReports(state,importTarget.current,pending);await commit(result.state);dialog.current?.close();setPending([]);setPasted('');setMessage(`Imported ${result.added} reports; skipped ${result.duplicates} duplicates.`);}catch(e){setImportError((e as Error).message);}}}>Confirm import</button><button type="button" onClick={()=>dialog.current?.close()}>Cancel</button></div></dialog></div>;
}
function CampaignView({campaign,onExport}:{campaign:Campaign;onExport:()=>void}){
 const reports=useMemo(()=>campaign.reports.map(x=>parseReport(x.text,x.filename)).sort((a,b)=>a.turn-b.turn),[campaign.reports]);
 const [turn,setTurn]=useState<number|null>(null),[baseline,setBaseline]=useState<number|null>(null),[view,setView]=useState('map'),[selected,setSelected]=useState('AAL'),[query,setQuery]=useState(''),[filter,setFilter]=useState('mine'),[mobile,setMobile]=useState(false);
 const sourceDialog=useRef<HTMLDialogElement>(null);
 const r=reports.find(r=>r.turn===turn)||reports.at(-1);const older=reports.filter(p=>r&&p.turn<r.turn);const previous=older.find(p=>p.turn===baseline)||older.at(-1)||null;
 if(!r)return <section className="empty"><p className="eyebrow">{campaign.game} · Player {campaign.player}</p><h1>{campaign.name}</h1><p>This campaign is ready. Import a turn report to populate its map, briefing, and forces ledger.</p></section>;
 const m=metrics(r),before=previous?metrics(previous):null,changes=compare(previous,r),s=r.spaces[selected],geo=atlas[selected];
 const highlighted=mapChanges(previous,r);
 const codes=Object.keys(atlas).filter(c=>query?`${c} ${name(c)}`.toLowerCase().includes(query.toLowerCase()):filter==='all'||filter==='mine'&&!!r.own[c]||filter==='visible'&&r.spaces[c]?.visible||filter==='changed'&&!!highlighted[c]);
 const links=(items:string[])=>items.length?items.map(code=><button type="button" className="chip" key={code} onClick={()=>{setSelected(code);setView('map');}}>{code} · {name(code)}</button>):<p>None reported.</p>;
 return <><div className="campaign-heading"><div><p className="eyebrow">{r.game} / Player {r.player}</p><h1>{campaign.name}</h1><p>{r.position.replaceAll('/',' / ')} · Report {r.turn}{previous?` · Changes since report ${previous.turn}`:' · Opening report'}</p></div><div className="turn-controls"><label>Report<select name="turn" value={r.turn} onChange={e=>{setTurn(+e.target.value);setBaseline(null);}}>{reports.map(x=><option key={x.turn} value={x.turn}>Turn {x.turn}</option>)}</select></label><label>Compare<select name="compare" disabled={!older.length} value={previous?.turn??''} onChange={e=>setBaseline(+e.target.value)}>{!older.length&&<option value="">Opening</option>}{older.map(x=><option key={x.turn} value={x.turn}>Turn {x.turn}</option>)}</select></label></div></div>
 <div className="metrics-wrapper"><div className="metrics">{[['occupied','Occupied countries'],['industry','Usable industry'],['cash','Reserve dollars'],['suppressedIndustry','Suppressed industry'],['suppressedAir','Recovering air force']].map(([k,label])=><div className="metric" key={k}><p>{label}</p><div className="metric-value">{num(m[k])}</div><p>{before?`${m[k]-before[k]>0?'+':''}${num(m[k]-before[k])} since turn ${previous?.turn}`:'Opening report'}</p></div>)}</div></div>
 <Multipliers report={r} previous={previous}/>
 <div className="nav-row"><button type="button" className="mobile-menu" aria-expanded={mobile} aria-controls="views" onClick={()=>setMobile(!mobile)}>☰ Views</button><nav id="views" className={mobile?'open':''} aria-label="Campaign views">{[['map','Map & intelligence'],['briefing','Turn briefing'],['forces','Forces ledger']].map(([id,label])=><button type="button" key={id} aria-current={view===id?'page':undefined} onClick={()=>{setView(id);setMobile(false);}}>{label}</button>)}</nav><button type="button" onClick={()=>sourceDialog.current?.showModal()}>Read source report</button></div>
 {view==='map'&&<section className="workspace"><aside className="roster"><h2>Spaces <small>{codes.length}</small></h2><input aria-label="Search spaces" name="search" placeholder="Find a country or sea…" value={query} onChange={e=>setQuery(e.target.value)}/><select name="filter" aria-label="Filter spaces" value={filter} onChange={e=>setFilter(e.target.value)}><option value="mine">Under my control</option><option value="all">All spaces</option><option value="visible">Visible intelligence</option><option value="changed">Turn changes</option></select><div className="space-list">{codes.map(c=><button type="button" key={c} aria-pressed={selected===c} onClick={()=>setSelected(c)}><strong>{name(c)}</strong><small>{c} · {ownership(r,c)}</small></button>)}{!codes.length&&<p>No matching spaces.</p>}</div></aside><div className="map-column"><h2>Operations map</h2><OperationsMap previous={previous} atlas={atlas} report={r} selected={selected} onSelect={setSelected}/></div><aside className="detail"><p className="eyebrow">{selected} / {selected.startsWith('W')?'Sea space':'Country'}</p><h2>{geo.name}</h2><p>{ownership(r,selected)}</p><ForcesInRange report={r} atlas={atlas} selected={selected}/>{previous&&<section className="selected-changes"><h3>Changes since turn {previous.turn}</h3>{highlighted[selected]?.length?<><ul>{highlighted[selected].map(change=><li key={change.label}>{change.label}</li>)}</ul><p>Before: {ownership(previous,selected)}.</p><p>Now: {ownership(r,selected)}.</p></>:<p>No ownership, control, visibility, or reported-force change.</p>}</section>}{s?.visible?<><h3>Known forces · Turn {r.turn}</h3><dl className="force-grid">{fields.map(f=><div key={f}><dt>{f}</dt><dd>{num(s.values[f])}{(s.suppressed[f]??0)>0&&<small> + {num(s.suppressed[f])} suppressed</small>}</dd></div>)}</dl>{s.fleets.length>0&&<><h3>Reported fleets</h3>{s.fleets.map((f,i)=><p key={i}>Player {f.player}: Army {num(f.values.Army)}, Navy {num(f.values.Navy)}, Air {num(f.values.AirF)}</p>)}</>}</>:<p>Forces unknown in this report.</p>}<h3>Surface connections</h3><div className="chips">{links(geo.surface)}</div><h3>Air connections</h3><div className="chips">{links(geo.air)}</div>{geo.canals.map(c=><p key={c.target}>Canal to {name(c.target)} via {name(c.gate)}.</p>)}<p>Connections describe geography. Unit rules, canal control, and permissions still apply.</p></aside></section>}
 {view==='briefing'&&<section className="briefing"><div><h2>Turn {r.turn} briefing</h2><p>{r.due}</p>{!previous&&<p>Select a later report to see changes.</p>}{[['captures','Countries captured'],['lost','Countries lost'],['controlGained','Minor control gained'],['controlLost','Minor control lost']].map(([k,title])=><section key={k}><h3>{title}</h3><div className="chips">{links(changes[k as keyof typeof changes])}</div></section>)}</div><div><h2>Orders & diplomacy</h2><p>Reserve spies: {r.Spies} · Counterspies: {r.CounterSpies}</p><p>Declared allies: {r.diplomacy.allies?.join(', ')||'None'}. These declarations do not share app data.</p><h3>Rejected orders</h3>{r.errors.length?<ul>{r.errors.map((e,i)=><li key={i}>{e}</li>)}</ul>:<p>None reported.</p>}<h3>Historical order echo</h3><pre>{r.orderEcho||'No order echo in this report.'}</pre></div></section>}
 {view==='forces'&&<section className="ledger"><div className="table-heading"><div><h2>Forces under your control</h2><p>Command-table values. Suppressed assets are separate.</p></div><button type="button" onClick={()=>download(`${r.game}-turn-${r.turn}-forces.csv`,[['Code','Name','Kind',...fields],...Object.values(r.own).map(s=>[s.code,name(s.code),s.kind,...fields.map(f=>s.values[f]??0)])].map(row=>row.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\r\n'),'text/csv')}>Export CSV</button></div><div className="table-scroll"><table><thead><tr><th>Space</th><th>Control</th>{fields.map(f=><th key={f}>{f}</th>)}</tr></thead><tbody>{Object.values(r.own).map(s=><tr key={s.code}><td><button type="button" className="text-button" onClick={()=>{setSelected(s.code);setView('map');}}>{name(s.code)} · {s.code}</button></td><td>{s.kind}</td>{fields.map(f=><td key={f}>{num(s.values[f])}</td>)}</tr>)}</tbody><tfoot><tr><th>Total</th><td></td>{fields.map(f=><th key={f}>{num(r.totals[f])}</th>)}</tr></tfoot></table></div></section>}
 <div className="campaign-actions"><button type="button" onClick={onExport}>Export campaign backup</button><p>{reports.length} reports in this campaign.</p></div><dialog ref={sourceDialog} className="source-dialog" aria-labelledby="source-title"><div className="source-dialog-header"><h2 id="source-title">{r.game} · Report {r.turn}</h2><button type="button" onClick={()=>sourceDialog.current?.close()}>Close</button></div><pre className="source-dialog-body" tabIndex={0} role="region" aria-label="Source report text">{r.raw}</pre></dialog></>;
}
function ownership(r:Report,code:string){const s=r.spaces[code];return code.startsWith('W')?'Sea space':!s?'Not reported':s.owner?`Occupied by player ${s.owner}`:s.controller?`Minor · player ${s.controller} control`:'Minor · control unknown';}
