"use client";
import {useRef} from 'react';
import type {Geography,Report} from '../lib/wwbp/types';
import {categoryLabels,turnInformation,type ChangeCategory} from '../lib/turn-information';
export default function ChangeBrowser({report,previous,atlas,category,onCategory,selected,onSelect}:{report:Report;previous:Report|null;atlas:Record<string,Geography>;category:ChangeCategory|null;onCategory:(c:ChangeCategory|null)=>void;selected:string;onSelect:(code:string)=>void}){
 const dialog=useRef<HTMLDialogElement>(null),changes=turnInformation(previous,report);
 const codes=(c:ChangeCategory)=>c==='ownership'?changes.ownership.map(r=>r.code):changes[c];
 const select=(code:string)=>{onSelect(code);dialog.current?.close();};
 return <><div className="change-toolbar" aria-label="Change categories">{(Object.keys(categoryLabels) as ChangeCategory[]).map(c=><button key={c} type="button" disabled={!previous} aria-pressed={category===c} onClick={()=>{onCategory(c);if(c==='ownership')dialog.current?.showModal();}}>{categoryLabels[c]} ({codes(c).length})</button>)}{category&&<button type="button" onClick={()=>onCategory(null)}>Hide highlights</button>}</div><p className="change-explanation">{previous?'Comparing turn '+previous.turn+' → '+report.turn+'. New information means changed reported forces, industry, or intelligence in spaces visible in both reports.':'Import an earlier turn to compare.'}</p>{category&&previous&&<div className="change-key"><h3 id="changed-spaces-title" className="changed-spaces-title">{categoryLabels[category]} · All matching spaces</h3><p>{category==='ownership'?'Purple rings show ownership/control changes.':'Blue diamonds show information or visibility gained; dashed rings show visibility lost.'} Select a space for details. Scroll to see the full list.</p><div className="change-spaces" role="group" aria-labelledby="changed-spaces-title">{codes(category).filter(code=>atlas[code]).map(code=><button type="button" key={code} aria-pressed={selected===code} onClick={()=>onSelect(code)}>{code} · {atlas[code].name}</button>)}{!codes(category).length&&<p>No changes in this category.</p>}</div></div>}
 <dialog ref={dialog} className="range-dialog ownership-dialog" aria-labelledby="ownership-title"><header className="source-dialog-header"><div><h2 id="ownership-title">Changed ownership</h2><p>{report.game} · Turn {previous?.turn} → {report.turn}</p></div><button type="button" onClick={()=>dialog.current?.close()}>Close</button></header><div className="range-body"><p>Occupation and minor control are different. These are changes between reports; a battle or transfer is not always distinguishable. Unknown control is never treated as a confirmed change of player.</p><div className="range-table-wrap"><table className="ownership-table"><thead><tr><th>Space</th><th>Previous · Turn {previous?.turn}</th><th>Current · Turn {report.turn}</th><th>Change</th></tr></thead><tbody>{changes.ownership.map(row=><tr key={row.code}><td><button type="button" className="text-button" onClick={()=>select(row.code)}>{row.code} · {atlas[row.code]?.name||row.code}</button></td><td>{row.before}</td><td>{row.after}</td><td>{row.type}</td></tr>)}</tbody></table></div>{!changes.ownership.length&&<p>No ownership or control changes reported.</p>}<p>Select a space to close this report and inspect it on the map.</p></div></dialog></>;
}
