"use client";
import {useEffect,useMemo,useState} from 'react';
import type {Campaign,Geography,Report} from '../lib/wwbp/types';
import {parseReport} from '../lib/wwbp/parser';
import {scenarioEvidenceKey} from '../lib/scenario-storage';
import {newTurnPlan} from '../lib/turn-plan-storage';
import {TURN_MODEL_VERSION,type TurnPlan,type ExpectedContribution,type BattleReview} from '../lib/turn-plan-types';
import {analyzeTurnPlan,previewQuantity,orderRoles,type OrderRef,type TurnAnalysis} from '../lib/turn-analysis';
import {roles,defenseFields,type BattleRole} from '../lib/scenario-types';
import {displayNumber as num} from '../lib/battle-scenarios';

type Props={campaign:Campaign;referenceTurn:number|null;atlas:Record<string,Geography>;busy:boolean;onSave:(plan:TurnPlan)=>Promise<void>;onRemove:(id:string)=>Promise<void>;onDirty:(dirty:boolean)=>void};
const emptyReview=():BattleReview=>({defense:{},unknownOrders:false,isolated:false,note:''});
export default function CoordinatedOrders({campaign,referenceTurn,atlas,busy,onSave,onRemove,onDirty}:Props){
 const reports=useMemo(()=>[...campaign.reports,...(campaign.alliedReports||[])].map(r=>parseReport(r.text,r.filename)),[campaign.reports,campaign.alliedReports]);
 const saved=campaign.turnPlans||[];
 const [plan,setPlan]=useState<TurnPlan|null>(null),[dirty,setDirty]=useState(false),[message,setMessage]=useState(''),[deleting,setDeleting]=useState(false);
 useEffect(()=>{onDirty(dirty);return()=>onDirty(false);},[dirty,onDirty]);
 useEffect(()=>{if(!dirty)return;const stop=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',stop);return()=>window.removeEventListener('beforeunload',stop);},[dirty]);
 const change=(next:TurnPlan)=>{setPlan(next);setDirty(true);setMessage('');};
 const turns=[...new Set(reports.map(r=>r.turn))].sort((a,b)=>b-a);
 async function save(){if(!plan)return;try{const next={...plan,name:plan.name.trim()||`Coordinated turn ${plan.orderTurn}`,updatedAt:new Date().toISOString()};await onSave(next);setPlan(next);setDirty(false);setMessage('Coordinated plan saved.');}catch(e){setMessage((e as Error).message);}}
 return <section className="battle-scenarios coordinated-orders" aria-labelledby="turn-plan-title">
  <div><p className="eyebrow">{campaign.game} · Analysis</p><h1 id="turn-plan-title">Coordinated orders</h1><p>Check what each player actually plans to send. Find order errors, missing contributions, and attacks that may fail before submitting a turn.</p><p>These proposed orders stay in this analysis. Your regular order draft and historical report echoes are separate.</p></div>
  <div className="scenario-library"><label>Saved turn plan<select disabled={dirty||busy} value={plan&&saved.some(p=>p.id===plan.id)?plan.id:''} onChange={e=>{setPlan(saved.find(p=>p.id===e.target.value)||null);setMessage('');setDeleting(false);}}><option value="">Choose a saved turn plan</option>{saved.map(p=><option key={p.id} value={p.id}>{p.name} · Turn {p.orderTurn}</option>)}</select></label><button type="button" disabled={dirty||busy||!turns.length} onClick={()=>{change(newTurnPlan(referenceTurn??turns[0]));setDeleting(false);}}>New turn plan</button></div>
  {message&&<p role="status" className="scenario-note">{message}</p>}
  {plan?<>
   <div className="scenario-save"><p>{dirty?'Unsaved turn-plan changes.':'Saved turn plan.'} Save or discard before changing plans or campaigns.</p><div className="actions"><button type="button" className="primary" disabled={busy||!dirty} onClick={()=>void save()}>Save turn plan</button><button type="button" disabled={busy||!dirty} onClick={()=>{setPlan(saved.find(p=>p.id===plan.id)||null);setDirty(false);setMessage('Changes discarded.');}}>Discard turn-plan changes</button><button type="button" disabled={busy||dirty} onClick={()=>change({...structuredClone(plan),id:crypto.randomUUID(),name:`${plan.name.slice(0,60)} · alternative`})}>Copy turn plan</button>{saved.some(p=>p.id===plan.id)&&<button type="button" disabled={busy||dirty} onClick={()=>setDeleting(!deleting)}>Delete turn plan</button>}</div></div>
   {deleting&&<div className="scenario-note"><p>Delete “{plan.name}” and its saved proposed orders?</p><div className="actions"><button type="button" disabled={busy} onClick={async()=>{try{await onRemove(plan.id);setPlan(null);setDeleting(false);setMessage('Turn plan deleted.');}catch(e){setMessage((e as Error).message);}}}>Confirm turn-plan deletion</button><button type="button" onClick={()=>setDeleting(false)}>Cancel</button></div></div>}
   <fieldset className="scenario-editor" disabled={busy}><PlanEditor key={plan.id} plan={plan} campaign={campaign} reports={reports} atlas={atlas} turns={turns} change={change}/></fieldset>
  </>:<p className="allied-empty">{turns.length?'Create a turn plan, add each participating player, then paste their proposed ORDERS.':'Import an own or allied report to start a turn plan.'}</p>}
 </section>;
}

function usePlanEvidence(reports:Report[],turn:number){
 const input=useMemo(()=>({reports,turn}),[reports,turn]);
 const [state,setState]=useState<{input:typeof input;key:string;error:string}|null>(null);
 useEffect(()=>{let active=true;scenarioEvidenceKey(reports,turn,[]).then(key=>{if(active)setState({input,key,error:''});}).catch(()=>{if(active)setState({input,key:'',error:'Could not verify source revisions. Reload before analyzing.'});});return()=>{active=false;};},[input,reports,turn]);
 return state?.input===input?state:{key:'',error:''};
}
function openAnchor(id:string){const el=document.getElementById(id);if(!el)return;for(let p=el.parentElement;p;p=p.parentElement)if(p.tagName==='DETAILS')(p as HTMLDetailsElement).open=true;el.scrollIntoView({block:'center'});el.focus({preventScroll:true});}
function OrderLinks({refs}:{refs:OrderRef[]}){return <span className="turn-order-links">{refs.map(r=><a key={r.id} href={`#turn-order-${r.id}`} onClick={e=>{e.preventDefault();openAnchor(`turn-order-${r.id}`);}}>P{r.player} · line {r.line} · {r.token}</a>)}</span>;}
function PlanEditor({plan:p,campaign,reports,atlas,turns,change}:{plan:TurnPlan;campaign:Campaign;reports:Report[];atlas:Record<string,Geography>;turns:number[];change:(p:TurnPlan)=>void}){
 const evidence=usePlanEvidence(reports,p.baseTurn);
 const result=useMemo(()=>analyzeTurnPlan({...p,name:p.name.trim()||'Untitled turn plan'},reports,campaign.game,atlas,evidence.key),[p,reports,campaign.game,atlas,evidence.key]);
 const patch=(next:Partial<TurnPlan>)=>change({...p,...next});
 const [addPlayer,setAddPlayer]=useState(''),[previewRef,setPreviewRef]=useState(''),[previewAmount,setPreviewAmount]=useState('');
 const available=reports.filter(r=>r.turn===p.baseTurn&&!p.sets.some(s=>s.player===r.player));
 const selected=available.find(r=>String(r.player)===addPlayer)||available[0];
 const chosen=result.orders.find(o=>o.id===previewRef&&orderRoles[o.action||'']&&!o.standing);
 let preview:TurnAnalysis|null=null,previewError='';
 if(chosen&&previewAmount){try{preview=analyzeTurnPlan(previewQuantity(p,chosen,Number(previewAmount)),reports,campaign.game,atlas,evidence.key);}catch(e){previewError=(e as Error).message;}}
 const invalid=result.findings.filter(f=>f.kind==='error').length,ready=result.battles.filter(b=>b.estimates.length).length;
 return <>
  <div className="scenario-grid"><label>Turn-plan name<input maxLength={80} value={p.name} onChange={e=>patch({name:e.target.value})}/></label><label>Base report turn<select value={p.baseTurn} onChange={e=>patch({baseTurn:+e.target.value,orderTurn:+e.target.value+1,evidenceKey:'',choices:{},reviews:{}})}>{[...new Set([...turns,p.baseTurn])].sort((a,b)=>b-a).map(t=><option key={t} value={t}>Turn {t}</option>)}</select></label></div>
  <p className="scenario-note">{campaign.game} · Base report turn {p.baseTurn} → intended order turn {p.orderTurn}. Every player’s report must match this base turn.</p>
  <div className="scenario-live"><p role="status">{invalid} order error{invalid===1?'':'s'} · {ready} of {result.battles.length} land engagements estimated</p><a href="#turn-findings">Findings</a><a href="#turn-battles">Battle estimates</a><a href="#turn-exposure">Remaining home defense</a></div>
  <div className="scenario-evidence-status"><p>{evidence.error||(!evidence.key?'Checking source revisions…':p.evidenceKey===evidence.key&&p.modelVersion===TURN_MODEL_VERSION?'Source revisions match this plan.':'Review needed: new plan or changed source reports.')}</p><button type="button" disabled={!evidence.key} onClick={()=>patch({evidenceKey:evidence.key,modelVersion:TURN_MODEL_VERSION,choices:{},sets:p.sets.map(s=>({...s,standingReviewed:false})),reviews:Object.fromEntries(Object.entries(p.reviews).map(([k,r])=>[k,{...r,unknownOrders:false,isolated:false}]))})}>Use current intelligence for turn plan</button></div>
  <details open className="scenario-section"><summary>1. Players and proposed orders ({p.sets.length})</summary>
   <p>Paste each player’s complete proposed order block. An empty field is missing input; use ORDERS and END on separate lines to explicitly propose no new orders. Existing defaults still apply.</p>
   <div className="scenario-library"><label>Add player from this turn<select value={selected?.player||''} onChange={e=>setAddPlayer(e.target.value)}><option value="">{available.length?'Choose a player':'No other reports for this turn'}</option>{available.map(r=><option key={r.player} value={r.player}>Player {r.player} · {r.position} · {r.filename}</option>)}</select></label><button type="button" disabled={!selected||p.sets.length>=50} onClick={()=>{if(selected)patch({sets:[...p.sets,{player:selected.player,reportTurn:selected.turn,text:'',standingReviewed:false}]});}}>Add player</button></div>
   {result.players.map(({set:s,report,check})=>{const savedDraft=campaign.orderDrafts?.find(d=>d.baseTurn===s.reportTurn);const update=(next:Partial<typeof s>)=>patch({sets:p.sets.map(x=>x.player===s.player?{...x,...next}:x)});return <details open className="turn-player" key={s.player} id={`turn-player-${s.player}`} tabIndex={-1}><summary>Player {s.player}{s.player===campaign.player?' · Your position':''} · Report turn {s.reportTurn}</summary>
    <label>Player {s.player} base report<select value={s.reportTurn} onChange={e=>update({reportTurn:+e.target.value,standingReviewed:false,copiedDraftAt:undefined})}>{[...new Set([...reports.filter(r=>r.player===s.player).map(r=>r.turn),s.reportTurn])].sort((a,b)=>b-a).map(t=><option key={t} value={t}>Turn {t}{t!==p.baseTurn?' · mismatched turn':''}</option>)}</select></label>
    <p>{report?.filename||'Associated report is missing.'}</p>
    <label>Player {s.player} proposed ORDERS<textarea spellCheck={false} rows={8} maxLength={100000} value={s.text} onChange={e=>update({text:e.target.value})} placeholder={'ORDERS\n@AAL AC10ALI\nEND'}/></label>
    <div className="actions"><button type="button" disabled={!!s.text.trim()} onClick={()=>update({text:'ORDERS\nEND'})}>Propose no new orders</button>{s.player===campaign.player&&<button type="button" disabled={!!s.text.trim()||!savedDraft} onClick={()=>{if(savedDraft)update({text:savedDraft.text,copiedDraftAt:savedDraft.updatedAt});}}>Copy saved own draft</button>}<button type="button" onClick={()=>patch({sets:p.sets.filter(x=>x.player!==s.player)})}>Remove Player {s.player}</button></div>
    {s.copiedDraftAt&&<p>Started from your saved draft revision {new Date(s.copiedDraftAt).toLocaleString()}. {savedDraft?.updatedAt!==s.copiedDraftAt?'That draft has since changed or is unavailable; this analysis copy remains independent.':'Further edits here remain independent.'}</p>}
    <label className="scenario-check"><input type="checkbox" checked={s.standingReviewed} onChange={e=>update({standingReviewed:e.target.checked})}/><span>Player {s.player}: I reviewed the active standing orders in the base report. No additional standing orders are omitted. Detected active standing orders still require manual resolution and will block affected estimates.</span></label>
    {report&&<details><summary>Read Player {s.player} base report</summary><pre className="turn-report" tabIndex={0}>{report.raw}</pre></details>}
    {check&&<details><summary>Interpreted orders, original lines, and resource budgets ({check.rows.length})</summary><p>Line numbers refer to the original pasted text above. Repeated sightings do not add units to a player’s command-table budget.</p><div className="table-scroll scenario-table"><table><thead><tr><th>Line / original token</th><th>Phase</th><th>Interpretation</th></tr></thead><tbody>{result.orders.filter(o=>o.player===s.player).map(o=><tr id={`turn-order-${o.id}`} tabIndex={-1} key={o.id}><th scope="row">{o.line} · {o.token}</th><td>{o.phase}</td><td>{o.description}{o.issues.map((issue,i)=><p key={i}>{issue.level==='error'?'Error':'Review'}: {issue.message}</p>)}</td></tr>)}</tbody></table></div><div className="table-scroll scenario-table"><table><thead><tr><th>Resource</th><th>Available</th><th>Ordered</th><th>Uncommitted</th></tr></thead><tbody>{check.budgets.map(b=><tr key={`${b.source}-${b.resource}`}><th scope="row">{b.source} · {b.resource}</th><td>{num(b.available)}</td><td>{num(b.used)}</td><td>{num(b.available-b.used)}</td></tr>)}</tbody></table></div></details>}
   </details>;})}
  </details>
  <details className="scenario-section"><summary>2. Expected contributions and specified threats</summary><p>Expectations check coordination; they do not commit units. A specified threat is a hypothetical enemy attack, kept separate from submitted player orders.</p>
   <ContributionEditor key={`expect-${p.baseTurn}`} title="Expected contribution" items={p.expected} atlas={atlas} players={reports.filter(r=>r.turn===p.baseTurn).map(r=>r.player)} onChange={expected=>patch({expected})}/>
   <ContributionEditor key={`threat-${p.baseTurn}`} title="Specified threat" items={p.threats} atlas={atlas} players={[]} threat onChange={threats=>patch({threats})}/>
  </details>
  <details className="scenario-section"><summary>3. Combined intelligence and source choices</summary><p>These are the reports behind this turn plan. Current conflicting observations require one source choice. Historical values are never silently reused as current forces.</p>
   {result.rows.filter(row=>result.orders.some(o=>o.source===row.group.code||o.target===row.group.code)||p.threats.some(t=>t.source===row.group.code||t.target===row.group.code)).map(row=><details key={row.group.id} id={`turn-evidence-${row.group.id}`} tabIndex={-1} className="scenario-source"><summary>{atlas[row.group.code]?.name||row.group.code} · {row.group.id} · Turn {row.group.turn}{row.historical?' · historical':''}{row.conflicts.length?' · conflicting sources':''}</summary>
    {!!row.conflicts.length&&<label>Choose source for {row.group.id}<select value={p.choices[row.group.id]||''} onChange={e=>{const choices={...p.choices};if(e.target.value)choices[row.group.id]=e.target.value;else delete choices[row.group.id];patch({choices});}}><option value="">Resolve this conflict</option>{row.group.candidates.map(o=><option key={o.source.id} value={o.source.id}>P{o.source.player} · {o.source.filename}</option>)}</select></label>}
    {row.group.candidates.map(o=><div key={o.source.id}><h3>Player {o.source.player} · Turn {o.source.turn} · {o.source.filename}</h3><pre>{o.record}</pre></div>)}
   </details>)}
  </details>
  <section className="scenario-result" id="turn-findings"><h2>Findings</h2><p>Order errors are definite validation failures. Battle outcomes are estimates. Assumptions and incomplete results identify what still needs review.</p>
   {result.findings.length?<ul className="turn-findings">{result.findings.map((f,i)=><li key={i}><strong>{({error:'Order error',coordination:'Coordination check',incomplete:'Incomplete',estimate:'Combat estimate',assumption:'Assumption'})[f.kind]}</strong><p>{f.message}</p><OrderLinks refs={f.refs}/>{f.player&&!f.refs.length&&p.sets.some(s=>s.player===f.player)&&<a href={`#turn-player-${f.player}`} onClick={e=>{e.preventDefault();openAnchor(`turn-player-${f.player}`);}}>Review Player {f.player}</a>}{f.target&&result.battles.some(b=>b.target===f.target)&&<a href={`#turn-battle-${f.target}`} onClick={e=>{e.preventDefault();openAnchor(`turn-battle-${f.target}`);}}>Review {f.target} engagement</a>}</li>)}</ul>:<p>{p.sets.length?'No order or coordination findings for the entered inputs. Omitted threats and orders remain unknown.':'Add proposed orders to begin checking.'}</p>}
  </section>
  <section className="scenario-section" id="turn-battles"><h2>Land engagements ({result.battles.length})</h2><p>Only ordered forces and specified threats participate. Support defends the destination; bombardment cannot capture it. Returns, counterattacks, and sea combat are outside this model.</p>
   {!result.battles.length&&<p>No land combat or support destinations yet. Add an attack order or a specified threat to test a defense.</p>}
   {result.battles.map(b=>{const r=p.reviews[b.target]||emptyReview(),owner=result.rows.find(row=>row.group.id===b.target)?.holder?.player,hasOrders=p.sets.some(s=>s.player===owner);const update=(next:Partial<BattleReview>)=>patch({reviews:{...p.reviews,[b.target]:{...r,...next}}});return <details open className="turn-engagement" id={`turn-battle-${b.target}`} key={b.target} tabIndex={-1}><summary>{atlas[b.target]?.name||b.target} · {b.target} — {b.estimates.length&&b.conditional?'Conditional: ':''}{b.estimates[1]?.outcome||'Incomplete'}</summary>
    <OrderLinks refs={b.refs}/>
    {!hasOrders&&<details open className="turn-assumptions"><summary>Assumed enemy defense · {r.unknownOrders?'reviewed':'review needed'}</summary><p>The defender’s proposed orders are missing. Enter the total local defense after movement, builds and recovery, before support from this plan. Reported forces alone do not establish this value.</p><div className="scenario-grid">{defenseFields.map(f=><label key={f}>{b.target} assumed {f}<input type="number" min={0} max={1000000} step={1} value={r.defense[f]??''} onChange={e=>{const defense={...r.defense};if(e.target.value==='')delete defense[f];else {const n=Number(e.target.value);if(!Number.isSafeInteger(n)||n<0||n>1_000_000)return;defense[f]=n;}update({defense});}}/></label>)}</div><label>Enemy behavior assumption for {b.target}<textarea rows={2} maxLength={2000} value={r.note} onChange={e=>update({note:e.target.value})}/></label><label className="scenario-check"><input type="checkbox" checked={r.unknownOrders} onChange={e=>update({unknownOrders:e.target.checked})}/><span>Use this explicit garrison assumption. Opposing orders are unknown, so this result is conditional.</span></label></details>}
    <label className="scenario-check"><input type="checkbox" checked={r.isolated} onChange={e=>update({isolated:e.target.checked})}/><span>I have reviewed omitted orders, enemy support, and diplomatic declarations for {b.target}. Assume they do not change this isolated engagement. Known unsupported interactions still block the estimate.</span></label>
    <p>Local pre-combat defense{b.errors.length?' (provisional)':''}: Army {num(b.defense.Army)} · AirF {num(b.defense.AirF)} · Navy {num(b.defense.Navy)} · ABMs {num(b.defense.ABMs)}. Listed support joins once during combat.</p>
    <a href={`#turn-evidence-${b.target}`} onClick={e=>{e.preventDefault();openAnchor(`turn-evidence-${b.target}`);}}>Inspect {b.target} intelligence sources</a>
    {b.errors.length?<ul>{b.errors.map((error,i)=><li key={i}>{error}</li>)}</ul>:<><p className="scenario-outcome">{b.conditional?'Conditional estimate: ':''}{b.estimates[1].outcome}</p><p>Central estimate: {num(b.estimates[1].conquer)} conquering army survive; {num(b.estimates[1].defenseArmy)} defending army remain.</p></>}
    <details><summary>Movement, builds, recovery, and combat progression</summary>{b.phases.length?<ul>{b.phases.map((text,i)=><li key={i}>{text}</li>)}</ul>:<p>No local changes calculated.</p>}{b.estimates[1]&&<ol className="scenario-stages">{b.estimates[1].stages.map(stage=><li key={stage.name}><h3>{stage.name}</h3><p>{stage.detail}</p></li>)}</ol>}</details>
    {!!b.estimates.length&&<details><summary>Hit-rate sensitivity and surviving commitments</summary><p>These are alternative approximate hit rates, not victory probabilities or outcome bounds.</p><div className="table-scroll scenario-table"><table><thead><tr><th>Assumed hit rate</th><th>Outcome</th><th>Conquering army</th><th>Defending army</th></tr></thead><tbody>{b.estimates.map(est=><tr key={est.rate}><th scope="row">{est.rate*100}%</th><td>{est.outcome}</td><td>{num(est.conquer)}</td><td>{num(est.defenseArmy)}</td></tr>)}</tbody></table></div><ul>{b.estimates[1].survivors.map(({force,remaining})=><li key={force.id}>P{force.player} · {force.code} · {roles[force.role].label}: {num(remaining)} of {num(force.quantity)} remain before returns{force.hypothetical?' (specified threat)':''}.</li>)}</ul></details>}
    {!!b.warnings.length&&<details><summary>Assumptions and model limits</summary><ul>{b.warnings.map((w,i)=><li key={i}>{w}</li>)}</ul></details>}
   </details>;})}
  </section>
  <details className="scenario-section" id="turn-exposure"><summary>Remaining home defense ({result.exposures.length})</summary><p>Departures can leave a country exposed. These values include supported movement, builds, and recovery, before combat. Add a specified threat above to test a particular attack.</p>{result.exposures.map(x=><div key={x.code}><h3>{atlas[x.code]?.name||x.code} · {x.code} · P{x.player}</h3>{x.errors.length?<p>Incomplete: {x.errors.join(' ')}</p>:<p>Army {num(x.defense.Army)} · AirF {num(x.defense.AirF)} · Navy {num(x.defense.Navy)} · ABMs {num(x.defense.ABMs)} before external support.</p>}<OrderLinks refs={x.refs}/></div>)}</details>
  <details className="scenario-section"><summary>Try a different commitment</summary><p>Preview one quantity change and compare it with this plan. The original pasted orders and saved plan stay untouched; budgets and coordination checks run again.</p><div className="scenario-grid"><label>Order to vary<select value={chosen?.id||''} onChange={e=>{setPreviewRef(e.target.value);setPreviewAmount('');}}><option value="">Choose a combat order</option>{result.orders.filter(o=>orderRoles[o.action||'']&&!o.standing).map(o=><option key={o.id} value={o.id}>P{o.player} · line {o.line} · {o.source} · {o.token}</option>)}</select></label><label>Preview quantity<input type="number" min={1} max={1000000} step={1} disabled={!chosen} value={previewAmount} onChange={e=>setPreviewAmount(e.target.value)}/></label></div>{previewError&&<p role="alert">{previewError}</p>}{preview&&<><div className="table-scroll scenario-table"><table><thead><tr><th>Engagement</th><th>Original plan</th><th>Quantity preview</th></tr></thead><tbody>{preview.battles.map(b=><tr key={b.target}><th scope="row">{b.target}</th><td>{result.battles.find(x=>x.target===b.target)?.estimates[1]?.outcome||'Incomplete'}</td><td>{b.estimates[1]?`${b.estimates[1].outcome} · ${num(b.estimates[1].conquer)} conquering army remain`:`Incomplete: ${b.errors.join(' ')}`}</td></tr>)}</tbody></table></div><ul>{preview.findings.filter(f=>['error','coordination','estimate'].includes(f.kind)).map((f,i)=><li key={i}>{f.message}</li>)}</ul><p>To keep a change, edit the proposed orders yourself or copy this plan as an alternative.</p></>}</details>
  <details className="scenario-section"><summary>Plan notes</summary><label>Coordination notes<textarea rows={3} maxLength={4000} value={p.notes} onChange={e=>patch({notes:e.target.value})}/></label></details>
 </>;
}

function ContributionEditor({title,items,atlas,players,threat=false,onChange}:{title:string;items:ExpectedContribution[];atlas:Record<string,Geography>;players:number[];threat?:boolean;onChange:(items:ExpectedContribution[])=>void}){
 const codes=Object.keys(atlas).sort((a,b)=>atlas[a].name.localeCompare(atlas[b].name));
 const [player,setPlayer]=useState(String(players[0]||2)),[source,setSource]=useState(''),[target,setTarget]=useState(''),[role,setRole]=useState<BattleRole>('conquer'),[quantity,setQuantity]=useState('1'),[error,setError]=useState('');
 function add(){const n=Number(quantity),who=Number(player);if(!Number.isSafeInteger(n)||n<1||n>1_000_000||!Number.isSafeInteger(who)||who<1||who>999||!atlas[source]||!atlas[target]||source===target){setError('Choose different source and target locations, a player from 1–999, and 1–1,000,000 whole units.');return;}onChange([...items,{id:crypto.randomUUID(),player:who,source,target,role,quantity:n}]);setError('');}
 return <section className="turn-contribution"><h3>{title}s ({items.length})</h3>{items.map(item=><div className="turn-contribution-row" key={item.id}><p>P{item.player} · {item.source} → {item.target} · {roles[item.role].label} · {item.quantity} units{threat?' · hypothetical':''}</p><button type="button" onClick={()=>onChange(items.filter(x=>x.id!==item.id))} aria-label={`Remove ${title.toLowerCase()} from ${item.source} to ${item.target}`}>Remove</button></div>)}<div className="scenario-grid"><label>{title} player<input type="number" min={1} max={999} value={player} onChange={e=>setPlayer(e.target.value)}/></label><label>{title} source<select value={source} onChange={e=>setSource(e.target.value)}><option value="">Choose source</option>{codes.map(c=><option key={c} value={c}>{atlas[c].name} · {c}</option>)}</select></label><label>{title} target<select value={target} onChange={e=>setTarget(e.target.value)}><option value="">Choose land target</option>{codes.filter(c=>!c.startsWith('W')).map(c=><option key={c} value={c}>{atlas[c].name} · {c}</option>)}</select></label><label>{title} role<select value={role} onChange={e=>setRole(e.target.value as BattleRole)}>{Object.entries(roles).filter(([,r])=>!threat||r.side==='attack').map(([k,r])=><option key={k} value={k}>{r.label}</option>)}</select></label><label>{title} quantity<input type="number" min={1} max={1000000} value={quantity} onChange={e=>setQuantity(e.target.value)}/></label></div>{error&&<p role="alert">{error}</p>}<button type="button" disabled={items.length>=100} onClick={add}>Add {title.toLowerCase()}</button></section>;
}
