"use client";
import {useRef,useState,useMemo} from 'react';
import type {Geography,Report} from '../lib/wwbp/types';
import {forcesInRange,type RangeRow} from '../lib/forces-in-range';
export default function ForcesInRange({report,atlas,selected}:{report:Report;atlas:Record<string,Geography>;selected:string}){
 const dialog=useRef<HTMLDialogElement>(null);const [target,setTarget]=useState(selected),[filter,setFilter]=useState('all'),[query,setQuery]=useState('');
 const result=useMemo(()=>forcesInRange(report,atlas,target),[report,atlas,target]);
 const matches=(player:number|null)=>filter==='all'||filter==='mine'&&player===report.player||filter==='others'&&player!=null&&player!==report.player||filter==='unknown'&&player==null||filter===String(player);
 const players=[...new Set([...result.rows,...result.gaps].map(r=>r.player).filter((p):p is number=>p!=null))].sort((a,b)=>a-b);
 function table(rows:RangeRow[]){return <div className="range-table-wrap"><table className="range-table"><thead><tr><th>Player</th><th>Source</th><th>Forces</th><th>What they can do</th></tr></thead><tbody>{rows.map((row,i)=><tr key={row.source+row.player+row.force+i}><td>{row.player??'?'}</td><td><abbr title={atlas[row.source].name}>{row.source}</abbr></td><td>{row.count}{row.force}</td><td>{row.action}</td></tr>)}</tbody></table></div>;}
 const local=result.rows.filter(r=>r.local&&matches(r.player)),incoming=result.rows.filter(r=>!r.local&&matches(r.player));
 const gaps=result.gaps.filter(g=>matches(g.player));
 return <><button type="button" className="range-open" onClick={()=>{setTarget(selected);setQuery('');setFilter('all');dialog.current?.showModal();}}>Forces in range</button><dialog ref={dialog} className="range-dialog" aria-labelledby="range-title"><header className="source-dialog-header"><div><h2 id="range-title">Forces in range · {target}</h2><p>{atlas[target]?.name} · {report.game} · Turn {report.turn}</p></div><button type="button" onClick={()=>dialog.current?.close()}>Close</button></header><div className="range-body"><div className="range-controls"><label>Find a space<input name="range-search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Code or country name"/></label><label>Target<select name="range-target" value={target} onChange={e=>setTarget(e.target.value)}>{Object.entries(atlas).filter(([code,g])=>code===target||(code+' '+g.name).toLowerCase().includes(query.toLowerCase())).map(([code,g])=><option key={code} value={code}>{code} · {g.name}</option>)}</select></label><label>Players<select name="range-player" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All players</option><option value="mine">My player ({report.player})</option><option value="others">Other players</option><option value="unknown">Unassigned / unknown</option>{players.map(p=><option key={p} value={p}>Player {p}</option>)}</select></label></div><p className="range-note">Known whole units at reported positions. Attack and support are alternative uses of the same forces. Orders, new builds, movements, and casualties can change participation. Standard WWBP rules.</p><section><h3>At the target</h3>{local.length?table(local):<p>No known nonzero forces for this filter. See intelligence gaps below.</p>}</section><section><h3>Within range</h3>{!incoming.length?<p>No known nonzero forces in range for this filter.</p>:[...new Set(incoming.map(r=>r.player))].map(player=><section className="range-player-group" key={player??'unknown'}><h4>{player==null?'Unassigned minor forces':'Player '+player+(player===report.player?' (you)':'')}</h4>{table(incoming.filter(r=>r.player===player))}</section>)}</section>{!target.startsWith('W')&&<p className="range-note">Sea landings face defending/supporting air and surviving coastal navy before fighting the target army. Army in the departure sea does not fight other army there.</p>}<details className="range-gaps"><summary>Intelligence gaps ({gaps.length})</summary><p>Unknown counts are not zero. Unknown owners may be hidden by a player filter; choose All players to see every gap.</p><ul>{gaps.map((gap,i)=><li key={gap.source+i}><abbr title={atlas[gap.source].name}>{gap.source}</abbr> · {gap.player==null?'Player unknown':'Player '+gap.player}: {gap.message}</li>)}</ul></details><p>A = Army · N = Navy · F = Air Force. Other players are not automatically enemies. Canal access and diplomatic declarations may be unknown.</p></div></dialog></>;
}
