"use client";
import {useEffect,useRef,useState} from 'react';
import type {Geography,Report} from '../lib/wwbp/types';
import {playerColor,unknownColor} from '../lib/map-legend';
import MapLegend from './map-legend';
export default function OperationsMap({atlas,report,selected,onSelect}:{atlas:Record<string,Geography>;report:Report;selected:string;onSelect:(c:string)=>void}){
 const [box,setBox]=useState({x:0,y:0,w:1936}),[aspect,setAspect]=useState(1.5);const host=useRef<HTMLDivElement>(null);const drag=useRef<{x:number;y:number;bx:number;by:number;moved:boolean}|null>(null);
 useEffect(()=>{const node=host.current;if(!node)return;const obs=new ResizeObserver(([entry])=>setAspect(entry.contentRect.width/entry.contentRect.height));obs.observe(node);return()=>obs.disconnect();},[]);
 const h=box.w/aspect;
 function zoom(factor:number){setBox(b=>{const w=Math.min(2150,Math.max(180,b.w*factor));return {x:b.x+(b.w-w)/2,y:b.y+(b.w-w)/aspect/2,w};});}
 function region(){const g=atlas[selected];setBox({x:g.x-250,y:g.y-250/aspect,w:500});}
 return <><div className="map-viewport" ref={host}><svg viewBox={`${box.x} ${box.y} ${box.w} ${h}`} aria-label="World operations map. Use the space list to select a country." onPointerDown={e=>{if(e.button!==0)return;drag.current={x:e.clientX,y:e.clientY,bx:box.x,by:box.y,moved:false};e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{const d=drag.current;if(!d)return;const scale=box.w/e.currentTarget.getBoundingClientRect().width;const dx=e.clientX-d.x,dy=e.clientY-d.y;if(Math.abs(dx)+Math.abs(dy)>4)d.moved=true;setBox(b=>({...b,x:d.bx-dx*scale,y:d.by-dy*scale}));}} onPointerUp={e=>{const d=drag.current;drag.current=null;if(d&&!d.moved){const rect=e.currentTarget.getBoundingClientRect();const x=box.x+(e.clientX-rect.left)*box.w/rect.width,y=box.y+(e.clientY-rect.top)*h/rect.height;const code=Object.keys(atlas).sort((a,b)=>Math.hypot(atlas[a].x-x,atlas[a].y-y)-Math.hypot(atlas[b].x-x,atlas[b].y-y))[0];if(Math.hypot(atlas[code].x-x,atlas[code].y-y)<12*box.w/rect.width)onSelect(code);}}} onPointerCancel={()=>{drag.current=null;}}><image href="/assets/world-map.png" width="1936" height="1280"/>{Object.entries(atlas).map(([code,g])=>{const s=report.spaces[code],id=s?.owner||s?.controller;const color=id?playerColor(id):unknownColor;const radius=(code===selected?6:4)*box.w/(host.current?.clientWidth||700);return <g key={code}><circle cx={g.x} cy={g.y} r={radius} fill={!s?.owner&&s?.controller?'white':color} stroke={code===selected?'#12281e':color} strokeWidth={radius/3}><title>{code} · {g.name}{id?` · Player ${id}`:''}</title></circle>{(code===selected||box.w<600)&&<text x={g.x+radius+2} y={g.y} fontSize={radius*2.2} className="map-label">{code}</text>}</g>;})}</svg></div><div className="map-tools"><p>Drag to pan. Zoom in to select small countries.</p><div className="actions"><button type="button" aria-label="Zoom in" onClick={()=>zoom(.7)}>+</button><button type="button" aria-label="Zoom out" onClick={()=>zoom(1.4)}>−</button><button type="button" onClick={()=>setBox({x:0,y:0,w:Math.max(1936,1280*aspect)})}>World</button><button type="button" onClick={region}>Selected region</button></div></div><MapLegend report={report}/></>;
}
